// → docs/spec/34-usage-metrics.md

export type UsageVerb =
  | 'view'
  | 'expand'
  | 'filter'
  | 'create'
  | 'edit'
  | 'accept'
  | 'reject'
  | 'defer'
  | 'waive'
  | 'abandon'
  | 'stop'
  | 'undo'
  | 'send'
  | 'close'
  | 'copy'
  | 'refresh'
  | 'spend'
  | 'open';

export const VERBS_BY_SUBJECT = {
  plan: ['view', 'expand', 'filter', 'edit', 'accept', 'reject', 'abandon', 'undo', 'close', 'open'],
  goal: ['view', 'expand', 'edit', 'accept', 'reject', 'waive', 'abandon', 'undo', 'close', 'open'],
  pr: ['view', 'edit', 'accept', 'send'],
  'pr-description': ['expand', 'create', 'accept', 'waive', 'close', 'open'],
  validation: [
    'view',
    'expand',
    'filter',
    'create',
    'edit',
    'accept',
    'reject',
    'defer',
    'waive',
    'stop',
    'undo',
    'close',
    'open',
  ],
  escalation: ['view', 'expand', 'edit', 'accept', 'reject', 'defer', 'send', 'close'],
  'human-task': ['view', 'expand', 'accept', 'reject'],
  ticket: ['view', 'expand', 'filter', 'create', 'accept', 'reject', 'waive', 'undo', 'close', 'open'],
  feature: ['view', 'expand', 'filter', 'defer', 'stop', 'undo', 'close', 'open'],
  agent: ['view', 'expand', 'edit', 'accept', 'reject', 'abandon', 'stop', 'send', 'close'],
  obstacle: ['view', 'expand', 'create', 'accept', 'reject', 'waive', 'stop', 'undo', 'close'],
  'local-run': ['view', 'expand', 'filter', 'create', 'edit', 'reject', 'stop', 'close', 'open'],
  job: ['view', 'expand', 'create', 'edit', 'stop', 'close'],
  retro: ['view', 'close'],
  scratchpad: ['view', 'edit', 'close'],
  insights: ['view', 'expand', 'filter', 'send', 'close'],
  pool: ['view', 'filter'],
  config: ['view', 'expand', 'filter', 'edit', 'accept', 'reject', 'abandon', 'undo', 'copy', 'refresh', 'close'],
  upgrade: ['view', 'accept', 'reject', 'defer', 'refresh', 'close'],
  pet: ['view', 'expand', 'filter', 'edit', 'abandon', 'spend', 'close'],
  fleet: ['view', 'filter', 'edit', 'stop', 'undo', 'open'],
  queue: ['view', 'close'],
  fault: ['view', 'waive', 'close'],
  signal: ['view', 'close'],
  environment: ['view', 'expand', 'edit', 'close'],
  record: ['view', 'expand', 'close'],
  placement: ['edit', 'accept', 'reject'],
  profile: ['accept', 'reject'],
  priority: ['create', 'undo'],
  intake: ['expand', 'edit', 'accept', 'waive', 'abandon', 'open'],
  criteria: ['expand', 'edit', 'abandon', 'close'],
  prediction: ['expand', 'create', 'accept', 'reject', 'waive', 'undo', 'close'],
  sequence: ['accept', 'reject', 'open'],
  watch: ['expand', 'create', 'edit', 'accept', 'reject', 'defer', 'waive', 'abandon', 'close'],
  schedule: ['expand', 'create', 'edit', 'abandon', 'stop', 'undo', 'close'],
  'review-thread': ['reject', 'undo'],
  'pr-assignee': ['accept', 'reject'],
  'bot-pr': ['view', 'create'],
  ejection: ['expand', 'accept', 'close', 'open'],
  theme: ['edit', 'accept', 'undo'],
  notification: ['edit', 'send'],
  project: ['accept'],
  scan: ['create'],
  demo: ['expand', 'create', 'close'],
  code: ['copy'],
  menu: ['expand', 'close'],
  reason: ['expand'],
} as const satisfies Record<string, readonly UsageVerb[]>;

export type UsageSubject = keyof typeof VERBS_BY_SUBJECT;

export const USAGE_SUBJECTS = Object.keys(VERBS_BY_SUBJECT) as UsageSubject[];

export type UsageEvent = {
  [S in UsageSubject]: `${S}.${(typeof VERBS_BY_SUBJECT)[S][number]}`;
}[UsageSubject];

export type UsageEventSource = 'ui' | 'record';

const EVENT_SOURCE = {
  'plan.view': 'ui',
  'plan.expand': 'ui',
  'plan.filter': 'ui',
  'plan.edit': 'record',
  'plan.accept': 'record',
  'plan.reject': 'ui',
  'plan.abandon': 'record',
  'plan.undo': 'ui',
  'plan.close': 'ui',
  'plan.open': 'ui',
  'goal.view': 'ui',
  'goal.expand': 'ui',
  'goal.edit': 'record',
  'goal.accept': 'record',
  'goal.reject': 'ui',
  'goal.waive': 'ui',
  'goal.abandon': 'record',
  'goal.undo': 'ui',
  'goal.close': 'ui',
  'goal.open': 'ui',
  'pr.view': 'ui',
  'pr.edit': 'ui',
  'pr.accept': 'record',
  'pr.send': 'record',
  'pr-description.expand': 'ui',
  'pr-description.create': 'record',
  'pr-description.accept': 'ui',
  'pr-description.waive': 'ui',
  'pr-description.close': 'ui',
  'pr-description.open': 'ui',
  'validation.view': 'ui',
  'validation.expand': 'ui',
  'validation.filter': 'ui',
  'validation.create': 'ui',
  'validation.edit': 'ui',
  'validation.accept': 'record',
  'validation.reject': 'record',
  'validation.defer': 'record',
  'validation.waive': 'record',
  'validation.stop': 'ui',
  'validation.undo': 'ui',
  'validation.close': 'ui',
  'validation.open': 'ui',
  'escalation.view': 'ui',
  'escalation.expand': 'ui',
  'escalation.edit': 'ui',
  'escalation.accept': 'record',
  'escalation.reject': 'record',
  'escalation.defer': 'ui',
  'escalation.send': 'record',
  'escalation.close': 'ui',
  'human-task.view': 'ui',
  'human-task.expand': 'ui',
  'human-task.accept': 'record',
  'human-task.reject': 'record',
  'ticket.view': 'ui',
  'ticket.expand': 'ui',
  'ticket.filter': 'ui',
  'ticket.create': 'record',
  'ticket.accept': 'ui',
  'ticket.reject': 'ui',
  'ticket.waive': 'ui',
  'ticket.undo': 'ui',
  'ticket.close': 'ui',
  'ticket.open': 'ui',
  'feature.view': 'ui',
  'feature.expand': 'ui',
  'feature.filter': 'ui',
  'feature.defer': 'ui',
  'feature.stop': 'ui',
  'feature.undo': 'ui',
  'feature.close': 'ui',
  'feature.open': 'ui',
  'agent.view': 'ui',
  'agent.expand': 'ui',
  'agent.edit': 'ui',
  'agent.accept': 'ui',
  'agent.reject': 'ui',
  'agent.abandon': 'ui',
  'agent.stop': 'record',
  'agent.send': 'ui',
  'agent.close': 'ui',
  'obstacle.view': 'ui',
  'obstacle.expand': 'ui',
  'obstacle.create': 'ui',
  'obstacle.accept': 'record',
  'obstacle.reject': 'ui',
  'obstacle.waive': 'record',
  'obstacle.stop': 'ui',
  'obstacle.undo': 'ui',
  'obstacle.close': 'ui',
  'local-run.view': 'ui',
  'local-run.expand': 'ui',
  'local-run.filter': 'ui',
  'local-run.create': 'record',
  'local-run.edit': 'ui',
  'local-run.reject': 'ui',
  'local-run.stop': 'record',
  'local-run.close': 'ui',
  'local-run.open': 'ui',
  'job.view': 'ui',
  'job.expand': 'ui',
  'job.create': 'record',
  'job.edit': 'ui',
  'job.stop': 'record',
  'job.close': 'ui',
  'retro.view': 'ui',
  'retro.close': 'ui',
  'scratchpad.view': 'ui',
  'scratchpad.edit': 'record',
  'scratchpad.close': 'ui',
  'insights.view': 'ui',
  'insights.expand': 'ui',
  'insights.close': 'ui',
  'insights.filter': 'ui',
  'insights.send': 'ui',
  'pool.view': 'ui',
  'pool.filter': 'ui',
  'config.view': 'ui',
  'config.expand': 'ui',
  'config.filter': 'ui',
  'config.edit': 'ui',
  'config.accept': 'ui',
  'config.reject': 'ui',
  'config.abandon': 'ui',
  'config.undo': 'ui',
  'config.copy': 'ui',
  'config.refresh': 'ui',
  'config.close': 'ui',
  'upgrade.view': 'ui',
  'upgrade.accept': 'record',
  'upgrade.reject': 'ui',
  'upgrade.defer': 'ui',
  'upgrade.refresh': 'ui',
  'upgrade.close': 'ui',
  'pet.view': 'ui',
  'pet.expand': 'ui',
  'pet.filter': 'ui',
  'pet.edit': 'record',
  'pet.abandon': 'ui',
  'pet.spend': 'ui',
  'pet.close': 'ui',
  'fleet.view': 'ui',
  'fleet.filter': 'ui',
  'fleet.edit': 'ui',
  'fleet.stop': 'ui',
  'fleet.undo': 'ui',
  'fleet.open': 'ui',
  'queue.view': 'ui',
  'queue.close': 'ui',
  'fault.view': 'ui',
  'fault.waive': 'ui',
  'fault.close': 'ui',
  'signal.view': 'ui',
  'signal.close': 'ui',
  'environment.view': 'ui',
  'environment.expand': 'ui',
  'environment.edit': 'ui',
  'environment.close': 'ui',
  'record.view': 'ui',
  'record.expand': 'ui',
  'record.close': 'ui',
  'placement.edit': 'ui',
  'placement.accept': 'ui',
  'placement.reject': 'ui',
  'profile.accept': 'ui',
  'profile.reject': 'ui',
  'priority.create': 'ui',
  'priority.undo': 'ui',
  'intake.expand': 'ui',
  'intake.edit': 'ui',
  'intake.accept': 'ui',
  'intake.waive': 'ui',
  'intake.abandon': 'ui',
  'intake.open': 'ui',
  'criteria.expand': 'ui',
  'criteria.edit': 'ui',
  'criteria.abandon': 'ui',
  'criteria.close': 'ui',
  'prediction.expand': 'ui',
  'prediction.create': 'ui',
  'prediction.accept': 'ui',
  'prediction.reject': 'ui',
  'prediction.waive': 'ui',
  'prediction.undo': 'ui',
  'prediction.close': 'ui',
  'sequence.accept': 'ui',
  'sequence.reject': 'ui',
  'sequence.open': 'ui',
  'watch.expand': 'ui',
  'watch.create': 'ui',
  'watch.edit': 'ui',
  'watch.accept': 'ui',
  'watch.reject': 'ui',
  'watch.defer': 'ui',
  'watch.waive': 'ui',
  'watch.abandon': 'ui',
  'watch.close': 'ui',
  'schedule.expand': 'ui',
  'schedule.create': 'ui',
  'schedule.edit': 'ui',
  'schedule.abandon': 'ui',
  'schedule.stop': 'ui',
  'schedule.undo': 'ui',
  'schedule.close': 'ui',
  'review-thread.reject': 'ui',
  'review-thread.undo': 'ui',
  'pr-assignee.accept': 'ui',
  'pr-assignee.reject': 'ui',
  'bot-pr.view': 'ui',
  'bot-pr.create': 'ui',
  'ejection.expand': 'ui',
  'ejection.accept': 'ui',
  'ejection.close': 'ui',
  'ejection.open': 'ui',
  'theme.edit': 'ui',
  'theme.accept': 'ui',
  'theme.undo': 'ui',
  'notification.edit': 'ui',
  'notification.send': 'ui',
  'project.accept': 'ui',
  'scan.create': 'ui',
  'demo.expand': 'ui',
  'demo.create': 'ui',
  'demo.close': 'ui',
  'code.copy': 'ui',
  'menu.expand': 'ui',
  'menu.close': 'ui',
  'reason.expand': 'ui',
} as const satisfies Record<UsageEvent, UsageEventSource>;

export type UiUsageEvent = {
  [E in UsageEvent]: (typeof EVENT_SOURCE)[E] extends 'ui' ? E : never;
}[UsageEvent];

type RecordUsageEvent = Exclude<UsageEvent, UiUsageEvent>;

type ViewUsageEvent = Extract<UsageEvent, `${string}.view`>;

export type ControlUsage = Exclude<UiUsageEvent, ViewUsageEvent> | { counted: RecordUsageEvent | ViewUsageEvent };

export function usageEventSource(event: UsageEvent): UsageEventSource {
  return EVENT_SOURCE[event];
}

export const PLACE_KEYS = [
  'overview',
  'tickets',
  'obstacles',
  'features',
  'bots',
  'insights',
  'pets',
  'config',
  'goal',
  'pr',
  'agent',
  'plan',
  'retro',
  'scratchpad',
  'ask',
  'hatch',
  'obstacle',
  'faults',
  'launch',
  'build',
  'local-run',
  'setup',
  'record',
  'upnext',
  'signals',
  'environments',
] as const;

export type PlaceKey = (typeof PLACE_KEYS)[number];

export type UsageArrival = 'linked' | 'direct';

export const SUBJECT_LABEL: Record<UsageSubject, string> = {
  plan: 'Plans',
  goal: 'Goals',
  pr: 'Pull requests',
  'pr-description': 'Pull request descriptions',
  validation: 'Validation',
  escalation: 'Escalations',
  'human-task': 'The bench',
  ticket: 'Tickets',
  feature: 'The feature board',
  agent: 'Agents',
  obstacle: 'Obstacles',
  'local-run': 'The local run',
  job: 'Jobs',
  retro: 'Retros',
  scratchpad: 'The scratchpad',
  insights: 'Insights',
  pool: 'The pool',
  config: 'Configuration',
  upgrade: 'The build',
  pet: 'The vivarium',
  fleet: 'The fleet',
  queue: 'Up next',
  fault: 'Faults',
  signal: 'World signals',
  environment: 'Environments',
  record: 'The record',
  placement: 'Placement',
  profile: 'Profiles',
  priority: 'Priority',
  intake: 'Intake',
  criteria: 'Goal criteria',
  prediction: 'Predictions',
  sequence: 'Story order',
  watch: 'Watches',
  schedule: 'Schedules',
  'review-thread': 'Review threads',
  'pr-assignee': 'Pull request assignees',
  'bot-pr': 'Bot pull requests',
  ejection: 'Ejected work',
  theme: 'The theme',
  notification: 'Notifications',
  project: 'The project checkout',
  scan: 'The scan',
  demo: 'The demo world',
  code: 'Code blocks',
  menu: 'The bar menu',
  reason: 'Row reasons',
};

export const VERB_LABEL: Record<UsageVerb, string> = {
  view: 'Reached',
  expand: 'Opened something inside',
  filter: 'Re-cut',
  create: 'Created',
  edit: 'Edited',
  accept: 'Accepted',
  reject: 'Rejected',
  defer: 'Deferred',
  waive: 'Waived',
  abandon: 'Abandoned',
  stop: 'Stopped',
  undo: 'Undone',
  send: 'Sent',
  close: 'Closed',
  copy: 'Copied',
  refresh: 'Refreshed',
  spend: 'Spent on',
  open: 'Taken out of the cockpit',
};
