import type { UsageEvent } from './events.js';

// → docs/spec/34-usage-metrics.md

export const USAGE_COPY: Record<UsageEvent, { label: string; blurb: string }> = {
  'plan.view': { label: 'Opened a plan', blurb: 'The plan page was reached' },
  'plan.expand': { label: 'Read into a plan', blurb: 'A part, a caveat or the write-up was opened' },
  'plan.edit': { label: 'Amended a plan', blurb: 'A correction to a plan that was already running' },
  'plan.accept': { label: 'Approved a plan', blurb: 'The decomposition was released to the fleet' },
  'plan.reject': { label: 'Sent a plan back', blurb: 'A replan: the planner runs again over what it produced' },
  'plan.abandon': { label: 'Abandoned a plan', blurb: 'The plan was dropped and nothing replaced it' },
  'goal.view': { label: 'Opened a goal', blurb: 'The goal page was reached' },
  'goal.expand': { label: 'Read into a goal', blurb: 'A section of the goal record was opened' },
  'goal.edit': { label: 'Instructed the fleet', blurb: 'A standing instruction was written on the goal' },
  'goal.accept': { label: 'Concluded a goal', blurb: 'The operator declared the work finished' },
  'goal.abandon': { label: 'Retired a goal', blurb: 'The goal was taken off the fleet without being finished' },
  'pr.view': { label: 'Opened a pull request', blurb: 'The pull request page was reached' },
  'pr.accept': { label: 'Authorised a landing', blurb: 'A merge, or a whole stack, was cleared to land' },
  'pr.send': { label: 'Sent a review reply', blurb: 'A drafted reply left the harness onto the thread' },
  'pr-description.create': {
    label: 'Wrote a description',
    blurb: 'A person wrote a pull request’s description themselves',
  },
  'pr-description.accept': {
    label: 'Used the agent’s description',
    blurb: 'A person took the agent’s draft instead of writing one',
  },
  'validation.view': { label: 'Opened validation', blurb: 'The goal’s checks were reached' },
  'validation.expand': { label: 'Read a check', blurb: 'One check’s procedure was opened' },
  'validation.accept': { label: 'Passed a check', blurb: 'The procedure was run and it did what it says' },
  'validation.reject': { label: 'Failed a check', blurb: 'The procedure was run and it did not' },
  'validation.defer': { label: 'Deferred a check', blurb: 'Put off, still owed' },
  'validation.waive': { label: 'Waived a check', blurb: 'Declared not needed — no longer owed' },
  'validation.undo': { label: 'Withdrew a reading', blurb: 'A previous result was taken back' },
  'escalation.view': { label: 'Opened an escalation', blurb: 'The inbox item was reached' },
  'escalation.accept': { label: 'Answered an escalation', blurb: 'The question was answered, or the act approved' },
  'escalation.reject': { label: 'Refused an escalation', blurb: 'The act was declined, or the item dismissed' },
  'escalation.send': { label: 'Replied to an agent', blurb: 'The answer was typed into the parked session' },
  'human-task.view': { label: 'Opened a bench item', blurb: 'The ask was reached' },
  'human-task.accept': { label: 'Did a bench item', blurb: 'The work only a person could do was done' },
  'human-task.reject': { label: 'Declined a bench item', blurb: 'The harness asked for the wrong thing' },
  'ticket.view': { label: 'Opened the backlog', blurb: 'The tracker items were reached' },
  'ticket.filter': { label: 'Re-cut the backlog', blurb: 'A filter, an ordering or a layout was changed' },
  'ticket.create': { label: 'Filed a ticket', blurb: 'A new tracker item was opened' },
  'feature.view': { label: 'Opened the feature board', blurb: 'The board was reached' },
  'feature.expand': { label: 'Read into a feature', blurb: 'One feature’s detail was opened' },
  'feature.filter': { label: 'Re-cut the feature board', blurb: 'A card was opened, or the order or filter changed' },
  'agent.view': { label: 'Opened an agent', blurb: 'A run’s console was reached' },
  'agent.expand': { label: 'Read into a run', blurb: 'The transcript, its files or its flags were opened' },
  'agent.send': { label: 'Steered an agent', blurb: 'Text was typed into a running session' },
  'agent.stop': { label: 'Stopped an agent', blurb: 'A running agent was halted by a person' },
  'obstacle.view': { label: 'Opened the obstacle board', blurb: 'What is in the fleet’s way was reached' },
  'obstacle.expand': { label: 'Read into an obstacle', blurb: 'One row’s keys, sightings or owner were opened' },
  'obstacle.accept': { label: 'Took an obstacle on', blurb: 'Somebody or something was named as owning it' },
  'obstacle.waive': { label: 'Retired an obstacle', blurb: 'Declared no longer in the way' },
  'local-run.view': { label: 'Opened the local run', blurb: 'The machine’s dev environment was reached' },
  'local-run.create': { label: 'Brought a branch up', blurb: 'A goal was checked out into the local environment' },
  'local-run.stop': { label: 'Took the local run down', blurb: 'The environment was stopped by a person' },
  'job.view': { label: 'Opened the job queue', blurb: 'The operator’s own queue was reached' },
  'job.create': { label: 'Launched a job', blurb: 'Work was queued that no ticket asked for' },
  'job.stop': { label: 'Stopped a job', blurb: 'A queued or running job was halted' },
  'retro.view': { label: 'Opened a retro', blurb: 'What the fleet learned on a goal was reached' },
  'scratchpad.view': { label: 'Opened the scratchpad', blurb: 'The shared notes were reached' },
  'scratchpad.edit': { label: 'Wrote in the scratchpad', blurb: 'The shared notes were changed' },
  'insights.view': { label: 'Opened Insights', blurb: 'A reading tab was reached' },
  'insights.filter': { label: 'Re-cut Insights', blurb: 'The window or a tab was changed' },
  'pool.view': { label: 'Opened the pool', blurb: 'The cross-fleet digest was reached' },
  'pool.filter': { label: 'Re-cut the pool', blurb: 'A fleet, a section or a day was changed' },
  'config.view': { label: 'Opened configuration', blurb: 'The settings were reached' },
  'config.edit': { label: 'Changed configuration', blurb: 'A key the harness reads was written' },
  'upgrade.view': { label: 'Opened the build', blurb: 'The harness’s own build was reached' },
  'upgrade.accept': { label: 'Accepted an upgrade', blurb: 'The fleet drained and the harness rebuilt itself' },
  'upgrade.reject': { label: 'Declined an upgrade', blurb: 'The available build was not taken' },
  'pet.view': { label: 'Opened the vivarium', blurb: 'The corner was reached' },
  'pet.edit': { label: 'Named a pet', blurb: 'A creature was renamed' },
  'plan.filter': { label: 'Moved around a plan', blurb: 'A rail jump, a proof cell or the regroup view was chosen' },
  'plan.undo': { label: 'Reset a regroup', blurb: 'A regroup draft was put back to the plan as it stands' },
  'plan.close': {
    label: 'Closed a plan',
    blurb: 'The plan, a drawer, its history or a draft part was shut without settling',
  },
  'goal.undo': { label: 'Took a goal act back', blurb: 'An instruction, a “finished” or a gate release was withdrawn' },
  'goal.waive': { label: 'Released an environment wait', blurb: 'The goal was declared not waiting on a deployment' },
  'goal.close': { label: 'Closed a goal section', blurb: 'A goal dialog was shut unsent, or a section folded away' },
  'pr.edit': { label: 'Changed a pull request', blurb: 'A reviewer was added, or the watch label put on or taken off' },
  'pr-description.expand': {
    label: 'Read the description drafts',
    blurb: 'The writer or the agent’s hidden draft was opened or closed',
  },
  'pr-description.waive': {
    label: 'Left a description as is',
    blurb: 'The findings against a description were dismissed',
  },
  'pr-description.close': { label: 'Closed the description writer', blurb: 'The writer was shut without saving' },
  'validation.create': {
    label: 'Started a validation run',
    blurb: 'A local run, a remote sheet or an accepted row was run',
  },
  'validation.edit': {
    label: 'Changed a check',
    blurb: 'A check was handed over, or a proposed or sheet row declined or put back',
  },
  'validation.filter': {
    label: 'Re-cut validation',
    blurb: 'Another environment, or one-at-a-time versus all, was shown',
  },
  'validation.stop': { label: 'Called a run off', blurb: 'A running validation was ended without a reading' },
  'escalation.expand': { label: 'Read into an ask', blurb: 'An ask or its questions were unfolded or folded' },
  'escalation.defer': { label: 'Held a countdown', blurb: 'An escalation’s clock was held for fifteen minutes' },
  'escalation.close': { label: 'Closed an ask', blurb: 'The ask or its questionnaire was shut unanswered' },
  'human-task.expand': { label: 'Opened a bench note', blurb: 'The note box for settling a bench item was opened' },
  'ticket.expand': { label: 'Read into a ticket', blurb: 'A reason, ignored work or a filing form was opened' },
  'ticket.accept': { label: 'Watched a ticket', blurb: 'The watch label was put on for pickup' },
  'ticket.reject': { label: 'Unwatched a ticket', blurb: 'The watch label was taken off' },
  'ticket.waive': { label: 'Ignored unrecorded work', blurb: 'Declared that no tracker item is wanted for it' },
  'ticket.undo': { label: 'Un-ignored unrecorded work', blurb: 'A previous ignore was taken back' },
  'ticket.close': {
    label: 'Closed a ticket form or fold',
    blurb: 'A filing form, a reason or the ignored work was shut',
  },
  'feature.stop': { label: 'Paused a feature', blurb: 'No work under the Feature is picked up' },
  'feature.defer': { label: 'Skipped a feature ask', blurb: 'An ask in Focus was set aside for now' },
  'feature.undo': { label: 'Brought a feature back', blurb: 'A pause or the skipped asks were taken back' },
  'agent.edit': { label: 'Lifted an agent’s profile', blurb: 'A run was stopped and handed to a bigger profile' },
  'agent.accept': { label: 'Settled an agent', blurb: 'A run was marked done, or a crashed one restored' },
  'agent.reject': {
    label: 'Requeued a crashed agent',
    blurb: 'Its conversation was dropped and the work queued again',
  },
  'agent.abandon': { label: 'Removed crashed work', blurb: 'A crashed agent’s work was abandoned' },
  'agent.close': { label: 'Closed an agent', blurb: 'The drawer, the eject dialog or the ended shifts were shut' },
  'obstacle.reject': { label: 'Declined an obstacle’s bug', blurb: 'A proposed bug for an obstacle was refused' },
  'obstacle.stop': { label: 'Muted an obstacle', blurb: 'The fleet stopped being told about it' },
  'obstacle.undo': { label: 'Unmuted an obstacle', blurb: 'A mute was taken back' },
  'local-run.expand': { label: 'Read into the local run', blurb: 'Earlier parts or its output were opened' },
  'local-run.filter': { label: 'Picked a local target', blurb: 'A goal or part was chosen in the picker' },
  'local-run.edit': { label: 'Refreshed the local run', blurb: 'The checkout was moved to its branch’s tip' },
  'local-run.reject': {
    label: 'Declined a local swap',
    blurb: 'The offer to swap or refresh the local run was declined',
  },
  'local-run.close': { label: 'Closed the local run', blurb: 'The panel or the earlier parts were shut' },
  'job.expand': { label: 'Opened a new brief', blurb: 'The brief form was shown or hidden' },
  'job.edit': { label: 'Edited a brief', blurb: 'An attachment was added to or removed from a brief' },
  'job.close': { label: 'Closed the launch desk', blurb: 'The panel was shut' },
  'retro.close': { label: 'Closed a retro', blurb: 'The retro was shut' },
  'scratchpad.close': { label: 'Closed the scratchpad', blurb: 'The notes were shut' },
  'insights.send': { label: 'Exported Insights', blurb: 'A tab was downloaded as a file' },
  'config.expand': {
    label: 'Read into configuration',
    blurb: 'Advanced keys, a prompt, the file preview or the review was opened',
  },
  'config.filter': {
    label: 'Re-cut configuration',
    blurb: 'A tab or group was changed, or the review left for the values',
  },
  'config.accept': {
    label: 'Applied configuration',
    blurb: 'A suggestion, a staged change, a reload or a finished setup was taken',
  },
  'config.reject': {
    label: 'Declined a setting',
    blurb: 'An offer was put aside, or edits kept over the file on disk',
  },
  'config.undo': { label: 'Took a setting back', blurb: 'A staged change or an applied fix was undone' },
  'config.abandon': { label: 'Discarded config edits', blurb: 'Staged or unsaved edits, or setup, were thrown away' },
  'config.copy': { label: 'Copied a command', blurb: 'A setup or fix command was copied' },
  'config.refresh': { label: 'Reloaded configuration', blurb: 'The config was re-read from disk' },
  'config.close': { label: 'Closed configuration', blurb: 'Setup, a prompt or the advanced keys were shut' },
  'upgrade.defer': { label: 'Snoozed an update', blurb: 'An available build or project pull was put off' },
  'upgrade.refresh': { label: 'Checked for a build', blurb: 'A fresh reading of the build was asked for' },
  'upgrade.close': { label: 'Closed the build', blurb: 'The panel was shut' },
  'pet.expand': { label: 'Opened an egg', blurb: 'An egg was hatched to reveal its creature' },
  'pet.filter': { label: 'Re-cut the vivarium', blurb: 'Blended pets shown or hidden, or a pet put out or taken in' },
  'pet.spend': { label: 'Fed a pet', blurb: 'Beats were spent growing a creature' },
  'pet.abandon': { label: 'Blended a pet', blurb: 'A duplicate creature was blended back into beats' },
  'pet.close': { label: 'Closed a hatch', blurb: 'The hatch was finished or skipped' },
  'fleet.view': { label: 'Opened the overview', blurb: 'The overview tab was reached' },
  'fleet.filter': { label: 'Re-cut the overview', blurb: 'Its shape was switched, or Focus moved to another ask' },
  'fleet.edit': { label: 'Changed the fleet cap', blurb: 'The number of concurrent agents was raised or lowered' },
  'fleet.stop': { label: 'Paused the fleet', blurb: 'New dispatch was paused by a person' },
  'fleet.undo': { label: 'Resumed the fleet', blurb: 'A pause on dispatch was lifted' },
  'queue.view': { label: 'Opened Up next', blurb: 'The dispatch queue was reached' },
  'queue.close': { label: 'Closed Up next', blurb: 'The panel was shut' },
  'fault.view': { label: 'Opened the fault log', blurb: 'The recorded faults were reached' },
  'fault.waive': { label: 'Cleared the fault log', blurb: 'Every recorded fault was deleted' },
  'fault.close': { label: 'Closed the fault log', blurb: 'The panel was shut' },
  'signal.view': { label: 'Opened world signals', blurb: 'The feed the queue is decided off was reached' },
  'signal.close': { label: 'Closed world signals', blurb: 'The panel was shut' },
  'environment.view': {
    label: 'Opened environments',
    blurb: 'The environment readings or tenant commands were reached',
  },
  'environment.expand': { label: 'Read tenant output', blurb: 'A tenant command’s output was followed to its tail' },
  'environment.edit': { label: 'Prepared a tenant', blurb: 'An environment’s tenant was provisioned or reseeded' },
  'environment.close': { label: 'Closed environments', blurb: 'The panel was shut' },
  'record.view': { label: 'Opened the record', blurb: 'What the harness did was reached' },
  'record.expand': { label: 'Read into the record', blurb: 'A root, or the list of goals, was opened' },
  'record.close': { label: 'Closed the record', blurb: 'The panel was shut' },
  'placement.accept': { label: 'Took the suggested place', blurb: 'The proposed parent or area path was applied' },
  'placement.edit': { label: 'Filed a goal elsewhere', blurb: 'A different parent or area path was picked' },
  'placement.reject': { label: 'Declined a placement', blurb: 'The goal was declared to need no parent or area path' },
  'profile.accept': { label: 'Took the proposed profile', blurb: 'The goal was pinned to the appraisal’s profile' },
  'profile.reject': { label: 'Kept the profile', blurb: 'The appraisal’s proposed profile was declined' },
  'priority.create': { label: 'Prioritised work', blurb: 'A goal or Feature was put first in the queue' },
  'priority.undo': { label: 'Dropped a priority', blurb: 'The queue went back to its natural order' },
  'intake.expand': { label: 'Began an intake', blurb: 'The prediction and criteria form was opened' },
  'intake.edit': { label: 'Recorded an intake', blurb: 'A prediction or criteria were written before planning' },
  'intake.accept': {
    label: 'Released to planning',
    blurb: 'Planning was started, or an unclear goal declared workable',
  },
  'intake.waive': { label: 'Skipped the intake', blurb: 'The goal went to planning with nothing written down' },
  'intake.abandon': { label: 'Dropped an intake draft', blurb: 'The intake form was backed out of unsaved' },
  'criteria.expand': { label: 'Opened the criteria', blurb: 'The criteria record or its writing form was opened' },
  'criteria.edit': { label: 'Wrote the criteria', blurb: 'A new version of what “done” means was appended' },
  'criteria.abandon': { label: 'Dropped a criteria draft', blurb: 'A criteria draft was cancelled unsaved' },
  'prediction.expand': { label: 'Opened a prediction', blurb: 'The composer or the review fold was opened' },
  'prediction.create': { label: 'Made a prediction', blurb: 'A prediction was written before the plan was shown' },
  'prediction.accept': { label: 'Marked a prediction matched', blurb: 'A prediction was marked as borne out' },
  'prediction.reject': { label: 'Marked a prediction missed', blurb: 'A prediction was marked as wrong' },
  'prediction.waive': { label: 'Marked a prediction moot', blurb: 'A prediction was marked not applicable' },
  'prediction.undo': { label: 'Unmarked a prediction', blurb: 'A mark on a prediction was taken off' },
  'sequence.accept': { label: 'Accepted a story order', blurb: 'The proposed story sequence was accepted' },
  'sequence.reject': { label: 'Ran stories unordered', blurb: 'The proposed story sequence was declined' },
  'watch.expand': { label: 'Opened a watch form', blurb: 'A signal or measure form was opened' },
  'watch.create': { label: 'Added a watch', blurb: 'A new signal or measure was saved and run' },
  'watch.edit': { label: 'Edited a watch', blurb: 'A check’s query or threshold was changed' },
  'watch.accept': { label: 'Accepted a watch', blurb: 'An agent-declared check was accepted and run' },
  'watch.reject': { label: 'Declined a watch', blurb: 'An agent-declared check was declined' },
  'watch.defer': { label: 'Extended a watch', blurb: 'A watch window was given more time' },
  'watch.waive': { label: 'Deleted a watch', blurb: 'A live check and its readings were dropped' },
  'watch.abandon': { label: 'Dropped a watch draft', blurb: 'An open watch form was cancelled unsaved' },
  'schedule.expand': { label: 'Opened a schedule form', blurb: 'The new-schedule form was shown' },
  'schedule.create': { label: 'Created a schedule', blurb: 'A recurring job was saved' },
  'schedule.edit': { label: 'Picked a cron example', blurb: 'An example schedule was filled into the form' },
  'schedule.stop': { label: 'Paused a schedule', blurb: 'It stopped firing, keeping the recurrence' },
  'schedule.undo': { label: 'Resumed a schedule', blurb: 'It started firing again' },
  'schedule.abandon': { label: 'Deleted a schedule', blurb: 'A recurrence was forgotten; jobs it queued are kept' },
  'review-thread.reject': { label: 'Reopened a thread', blurb: 'A review thread was put back to the fleet' },
  'review-thread.undo': { label: 'Withdrew a reopen', blurb: 'The thread was left as the provider has it' },
  'pr-assignee.accept': { label: 'Assigned a pull request', blurb: 'Someone from the shortlist was put on it' },
  'pr-assignee.reject': { label: 'Left it unassigned', blurb: 'The assign ask was declined' },
  'bot-pr.view': { label: 'Opened bot pull requests', blurb: 'The dependency-bot pull request tab was reached' },
  'bot-pr.create': { label: 'Asked for a risk read', blurb: 'An agent was sent to classify the bot pull requests' },
  'ejection.expand': { label: 'Opened a hand-back', blurb: 'The dialog for settling ejected work was opened' },
  'ejection.accept': { label: 'Handed work back', blurb: 'Ejected work was settled' },
  'ejection.close': { label: 'Closed a hand-back', blurb: 'The dialog was shut unsettled' },
  'theme.edit': { label: 'Picked a theme', blurb: 'A preset was chosen' },
  'theme.accept': { label: 'Saved a theme', blurb: 'The drafted theme was saved to this browser' },
  'theme.undo': { label: 'Reset the theme', blurb: 'A token, all tokens or unsaved changes were reverted' },
  'notification.edit': { label: 'Enabled notifications', blurb: 'Browser notifications were turned on' },
  'notification.send': { label: 'Sent a test notification', blurb: 'A test notification was raised' },
  'project.accept': { label: 'Pulled the project', blurb: 'The project checkout took its waiting commits' },
  'scan.create': { label: 'Ran a scan', blurb: 'A pulse was run on demand' },
  'demo.expand': { label: 'Opened the raw injector', blurb: 'The raw JSON event form was shown' },
  'demo.create': { label: 'Injected a demo event', blurb: 'A synthetic world event was injected' },
  'code.copy': { label: 'Copied a code block', blurb: 'A fenced block’s text was copied' },
  'menu.expand': { label: 'Opened the bar menu', blurb: 'The top bar’s More menu was toggled' },
  'reason.expand': { label: 'Read why a row is there', blurb: 'A row’s why-mark was pressed' },
  'validation.close': { label: 'Closed a check pane', blurb: 'The Checks card or a run pane was folded away' },
  'obstacle.close': { label: 'Folded an obstacle', blurb: 'A row’s detail or the ended section was folded' },
  'feature.close': { label: 'Folded a feature', blurb: 'One feature’s work on the tickets page was folded' },
  'criteria.close': { label: 'Closed the criteria', blurb: 'The criteria record was folded away' },
  'prediction.close': { label: 'Closed a prediction', blurb: 'The composer or the review fold was shut' },
  'schedule.close': { label: 'Closed a schedule form', blurb: 'The new-schedule form was hidden' },
  'demo.close': { label: 'Closed the raw injector', blurb: 'The raw JSON event form was hidden' },
  'watch.close': { label: 'Folded the signals', blurb: 'The goal’s signals section was folded away' },
  'plan.open': { label: 'Discussed a plan', blurb: 'The plan was taken into the operator’s own Claude Code' },
  'goal.open': {
    label: 'Asked about a goal',
    blurb: 'The goal’s record was taken into the operator’s own Claude Code',
  },
  'pr-description.open': {
    label: 'Had a description checked',
    blurb: 'A written description was taken into Claude Code to be read against the diff',
  },
  'validation.open': {
    label: 'Ran a check at the keyboard',
    blurb: 'A check was taken into the operator’s own Claude Code',
  },
  'ticket.open': { label: 'Opened the issue form', blurb: 'The LubbDubb tracker’s new-issue page was opened' },
  'feature.open': {
    label: 'Asked about a feature',
    blurb: 'The feature was taken into the operator’s own Claude Code',
  },
  'local-run.open': {
    label: 'Ran a goal locally',
    blurb: 'A goal’s local run was taken into the operator’s own Claude Code',
  },
  'fleet.open': { label: 'Asked about the fleet', blurb: 'A question was opened in the operator’s own Claude Code' },
  'intake.open': {
    label: 'Discussed an intake hold',
    blurb: 'The gaps were taken into the operator’s own Claude Code',
  },
  'sequence.open': {
    label: 'Argued with a story order',
    blurb: 'The order was taken into the operator’s own Claude Code',
  },
  'ejection.open': {
    label: 'Opened ejected work',
    blurb: 'The held worktree was opened in the operator’s own Claude Code',
  },
};
