import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { buildApp } from '../src/server/app.js';
import { buildSystem, type System } from '../src/system/system.js';
import { loadConfig } from '../src/config/config.js';
import { FakePtyBackend } from '../src/pty/fakeBackend.js';
import { FakeWorktreeManager } from '../src/worktree/fakeWorktreeManager.js';
import { Store } from '../src/store/store.js';
import { BotPrRiskDesk, RISK_BATCH_LIMIT } from '../src/botPrs/riskDesk.js';
import { releaseNotesInBody, releaseTags, riskBriefing, sourceRepoInBody } from '../src/botPrs/riskBrief.js';
import type { ErrorRecorder } from '../src/errorLog.js';
import { lineDiff } from '../src/botPrs/lineDiff.js';
import { readAzureBotPrDetail } from '../src/integrations/azure/botPulls.js';
import type { AzureDevOpsApi } from '../src/integrations/azure/azureDevOpsApi.js';
import type { BotPr, BotPullRequest, UpdateKind } from '../src/types.js';
import type { BotPrsPayload } from '../src/wire.js';

// → docs/spec/37-bot-prs.md#the-risk-summary

const RENOVATE_BODY = [
  '| Package | Change |',
  '|---|---|',
  '| [dotenv](https://github.com/motdotla/dotenv) | `16.4.5` -> `17.0.1` |',
  '',
  '---',
  '',
  '### Release Notes',
  '',
  '<details><summary>motdotla/dotenv (dotenv)</summary>',
  '',
  '### [`v17.0.0`](https://github.com/motdotla/dotenv/releases/tag/v17.0.0)',
  '',
  '- Default `quiet` to false',
  '</details>',
  '',
  '---',
  '',
  '### Configuration',
  '',
  'This PR was generated by [Renovate Bot](https://github.com/renovatebot/renovate).',
].join('\n');

test('release notes are cut out of a Renovate body, and a Dependabot one', () => {
  const notes = releaseNotesInBody(RENOVATE_BODY);
  assert.ok(notes !== null);
  assert.ok(notes?.startsWith('### Release Notes'));
  assert.ok(notes.includes('Default `quiet` to false'));
  assert.ok(!notes.includes('Configuration'), 'the footer is not part of the notes');

  const dependabot = [
    'Bumps axios from 1.7.3 to 1.7.4.',
    '<details>',
    '<summary>Release notes</summary>',
    '<p>Fix a redirect bug</p>',
    '</details>',
    '<details>',
    '<summary>Commits</summary>',
    '<li>abc</li>',
    '</details>',
  ].join('\n');
  const found = releaseNotesInBody(dependabot);
  assert.ok(found !== null);
  assert.ok(found?.includes('Fix a redirect bug'));
  assert.ok(!found.includes('abc'), 'the commit list is left out');

  assert.equal(releaseNotesInBody('No notes here.'), null);
  assert.equal(releaseNotesInBody(null), null);
});

test('the source repository is the first github link that is no bot’s, and tags are tried in three shapes', () => {
  assert.deepEqual(sourceRepoInBody(RENOVATE_BODY), { owner: 'motdotla', repo: 'dotenv' });
  assert.equal(sourceRepoInBody('Generated by https://github.com/renovatebot/renovate'), null);
  assert.deepEqual(releaseTags('dotenv', '17.0.1'), ['v17.0.1', '17.0.1', 'dotenv@17.0.1']);
  assert.deepEqual(releaseTags(null, 'v2.0.0'), ['v2.0.0', '2.0.0']);
  assert.deepEqual(releaseTags('x', null), []);
});

test('the briefing keeps a manifest’s diff and leaves a lockfile’s contents out', () => {
  const brief = riskBriefing([
    {
      pr: botPr(7, 'major'),
      detail: {
        body: null,
        files: [
          { path: 'package.json', additions: 1, deletions: 1, patch: '-"dotenv": "16.4.5"\n+"dotenv": "17.0.1"' },
          { path: 'web/package-lock.json', additions: 400, deletions: 380, patch: 'SECRET-LOCK-CONTENT' },
        ],
      },
      notes: null,
    },
  ]);
  assert.ok(brief.includes('### PR 7'));
  assert.ok(brief.includes('+"dotenv": "17.0.1"'));
  assert.ok(brief.includes('web/package-lock.json (+400 −380): a lockfile, contents left out'));
  assert.ok(!brief.includes('SECRET-LOCK-CONTENT'));
  assert.ok(brief.includes('None found.'), 'missing notes are said, not skipped');
});

test('a line diff is a unified patch with context, and nothing where nothing changed', () => {
  const before = [
    '{',
    '  "name": "app",',
    '  "deps": {',
    '    "dotenv": "16.4.5",',
    '    "zod": "3.0.0"',
    '  }',
    '}',
  ].join('\n');
  const after = before.replace('16.4.5', '17.0.1');
  const diff = lineDiff(before, after);
  assert.equal(diff.additions, 1);
  assert.equal(diff.deletions, 1);
  assert.equal(
    diff.patch,
    [
      '@@ -1,7 +1,7 @@',
      ' {',
      '   "name": "app",',
      '   "deps": {',
      '-    "dotenv": "16.4.5",',
      '+    "dotenv": "17.0.1",',
      '     "zod": "3.0.0"',
      '   }',
      ' }',
    ].join('\n'),
  );
  assert.equal(lineDiff(before, before).patch, null);
  assert.deepEqual(lineDiff('', 'a\nb\n'), { patch: '@@ -1,0 +1,2 @@\n+a\n+b', additions: 2, deletions: 0 });
});

test('azure diffs each changed manifest between the merge base and the head, and never reads a lockfile', async () => {
  const reads: string[] = [];
  const files: Record<string, string> = {
    'base:package.json': '{\n  "dotenv": "16.4.5"\n}\n',
    'head:package.json': '{\n  "dotenv": "17.0.1"\n}\n',
    'base:app.csproj': '<a v="1"/>\n',
    'head:src/app.csproj': '<a v="2"/>\n',
  };
  const api = {
    getPullBody: async () => 'body',
    listPullChanges: async () => ({
      base: 'base',
      head: 'head',
      files: [
        { path: 'package.json', from: null },
        { path: 'package-lock.json', from: null },
        { path: 'src/app.csproj', from: 'app.csproj' },
        { path: 'broken.json', from: null },
      ],
    }),
    getFileAtCommit: async (path: string, commit: string) => {
      reads.push(`${commit}:${path}`);
      if (path === 'broken.json') throw new Error('-> 403 Forbidden');
      return files[`${commit}:${path}`] ?? '';
    },
  } as unknown as AzureDevOpsApi;
  const detail = await readAzureBotPrDetail(api, 5);
  assert.equal(detail.body, 'body');
  assert.deepEqual(detail.files, [
    {
      path: 'package.json',
      additions: 1,
      deletions: 1,
      patch: '@@ -1,3 +1,3 @@\n {\n-  "dotenv": "16.4.5"\n+  "dotenv": "17.0.1"\n }',
    },
    { path: 'package-lock.json', additions: null, deletions: null, patch: null },
    {
      path: 'src/app.csproj',
      additions: 1,
      deletions: 1,
      patch: '@@ -1,1 +1,1 @@\n-<a v="1"/>\n+<a v="2"/>',
    },
    { path: 'broken.json', additions: null, deletions: null, patch: null },
  ]);
  assert.ok(!reads.some((r) => r.includes('package-lock')), 'a lockfile is never read');
  assert.ok(reads.includes('base:app.csproj'), 'a moved file is read at its old path on the base');
});

test('a batch takes at most twenty, majors first, and leaves out unclassified updates and read heads', async () => {
  const store = new Store(':memory:');
  const kinds: UpdateKind[] = ['patch', 'minor', 'major', 'unknown'];
  const prs = Array.from({ length: 30 }, (_, i) => pull(i + 1, kinds[i % kinds.length]!));
  const kindOf = (n: number): UpdateKind => kinds[(n - 1) % kinds.length]!;
  store.botPrRisks.recordRisk({ prNumber: 3, headSha: 'sha3', risk: 'low', summary: 'read', runId: 'old' });
  const desk = new BotPrRiskDesk({
    store,
    source: source(prs),
    authors: () => ['bot'],
    schedule: () => '',
    errors: noErrors(),
  });
  const outcome = await desk.request('operator');
  assert.equal(outcome.ok, true);
  if (!outcome.ok) return;
  const numbers = outcome.run.subjects.map((s) => s.number);
  assert.equal(numbers.length, RISK_BATCH_LIMIT);
  assert.ok(!numbers.includes(3), 'a head already read is not read again');
  assert.ok(numbers.every((n) => kindOf(n) !== 'unknown'));
  const majors = numbers.filter((n) => kindOf(n) === 'major');
  assert.deepEqual(numbers.slice(0, majors.length), majors, 'majors lead the batch');

  const second = await desk.request('operator');
  assert.equal(second.ok, false, 'one run out at a time');
  store.close();
});

test('the schedule opens a run when it comes round, and not before', async () => {
  const store = new Store(':memory:');
  const desk = new BotPrRiskDesk({
    store,
    source: source([pull(1, 'patch')]),
    authors: () => ['bot'],
    schedule: () => '0 8 * * *',
    errors: noErrors(),
  });
  await desk.run(new Date(2026, 8, 30, 7, 0));
  assert.equal(store.botPrRisks.openRunNow(), null);
  await desk.run(new Date(2026, 8, 30, 7, 59));
  assert.equal(store.botPrRisks.openRunNow(), null);
  await desk.run(new Date(2026, 8, 30, 8, 0));
  assert.equal(store.botPrRisks.openRunNow()?.trigger, 'schedule');
  store.close();
});

test('pressed, one desk agent reads the batch, its verdicts land on their heads, and a push unreads one', async () => {
  const backend = new FakePtyBackend();
  const system = build(backend);
  system.connector.inject({
    kind: 'new_pr',
    number: 7,
    title: 'Update dependency dotenv to v17',
    branch: 'renovate/dotenv-17.x',
    author: 'renovate[bot]',
    headSha: 'a1',
  });
  system.connector.inject({ kind: 'pr_body_edited', prNumber: 7, body: RENOVATE_BODY });
  system.connector.inject({
    kind: 'new_pr',
    number: 8,
    title: 'Update dependency axios to v1.7.4 (patch)',
    branch: 'renovate/axios',
    author: 'renovate[bot]',
    headSha: 'b1',
  });
  system.connector.inject({
    kind: 'new_pr',
    number: 9,
    title: 'Update all non-major dependencies',
    branch: 'renovate/all',
    author: 'renovate[bot]',
    headSha: 'c1',
  });
  const { app } = await buildApp(system);
  try {
    const pressed = await app.inject({ method: 'POST', url: '/api/bot-prs/risk' });
    assert.equal(pressed.statusCode, 200);
    assert.equal(pressed.json<{ prs: number }>().prs, 2, 'the unclassified group update is left out');
    assert.equal((await app.inject({ method: 'POST', url: '/api/bot-prs/risk' })).statusCode, 409);

    await system.harness.runCycle('manual');
    const tasks = system.store.tasks.listTasks().filter((t) => t.rule === 'bot-pr-risk');
    assert.equal(tasks.length, 1, 'one agent for the whole batch');
    const task = tasks[0]!;
    assert.ok(task.agentId);
    const prompt = system.store.tasks.getTask(task.id)?.prompt ?? '';
    assert.ok(prompt.includes('### PR 7') && prompt.includes('### PR 8'));
    assert.ok(prompt.includes('Default `quiet` to false'), 'the release notes ride in the prompt');
    assert.equal(system.store.botPrRisks.openRunNow()?.status, 'dispatched');

    const refused = system.agents.recordBotPrRisk(task.agentId, { prNumber: 9, risk: 'low', summary: 'x' });
    assert.equal(refused.ok, false, 'a pull request outside the batch is refused');
    const first = system.agents.recordBotPrRisk(task.agentId, {
      prNumber: 7,
      risk: 'high',
      summary: 'Major: quiet now defaults to false.',
    });
    assert.deepEqual(first, { ok: true, remaining: [8] });
    system.agents.recordBotPrRisk(task.agentId, { prNumber: 8, risk: 'low', summary: 'One redirect fix.' });

    const read = (await app.inject({ method: 'GET', url: '/api/bot-prs' })).json<BotPrsPayload>();
    const risks = Object.fromEntries(read.pullRequests.map((pr) => [pr.number, pr.risk?.risk ?? null]));
    assert.deepEqual(risks, { 7: 'high', 8: 'low', 9: null });

    system.connector.inject({ kind: 'pr_pushed', prNumber: 8, headSha: 'b2' });
    backend.last().emitExit(0);
    await delay(5);
    await system.harness.runCycle('manual');
    assert.equal(system.store.botPrRisks.openRunNow(), null, 'the run settles once its agent has ended');

    await delay(5);
    const again = await system.botPrRisks.request('operator');
    assert.equal(again.ok, true);
    if (again.ok)
      assert.deepEqual(again.run.subjects, [{ number: 8, headSha: 'b2', title: again.run.subjects[0]!.title }]);
  } finally {
    await app.close();
    system.store.close();
  }
});

function build(backend: FakePtyBackend): System {
  const dir = mkdtempSync(join(tmpdir(), 'lubbdubb-botrisk-'));
  return buildSystem(
    loadConfig({
      selfUpdate: { enabled: false } as never,
      auth: { enabled: false } as never,
      labelPrefix: '',
      dbPath: ':memory:',
      agentMode: 'raw',
      deskRoot: join(dir, 'desk'),
      worktreeRoot: join(dir, 'wt'),
      heartbeatIntervalMs: 999_999,
      botPrs: { authors: ['^renovate\\[bot\\]$'], riskSchedule: '' },
    }),
    { worktrees: new FakeWorktreeManager(), backend, errorMirror: () => {} },
  );
}

function botPr(number: number, kind: UpdateKind): BotPr {
  return {
    number,
    title: `Update dependency pkg${number}`,
    author: 'renovate[bot]',
    ciStatus: 'passing',
    reviewers: [],
    viewerReviewing: false,
    url: null,
    createdAt: null,
    headSha: `sha${number}`,
    update: { kind, packageName: `pkg${number}`, from: '1.0.0', to: '1.0.1' },
  };
}

const TITLES: Record<UpdateKind, (n: number) => string> = {
  major: (n) => `Update dependency pkg${n} to v${n + 1}`,
  minor: (n) => `Update dependency pkg${n} to v1.${n}.0 (minor)`,
  patch: (n) => `Update dependency pkg${n} to v1.0.${n} (patch)`,
  unknown: (n) => `Update group ${n}`,
};

function pull(number: number, kind: UpdateKind): BotPullRequest {
  return {
    number,
    title: TITLES[kind](number),
    author: 'bot',
    ciStatus: 'passing',
    reviewers: [],
    viewerReviewing: false,
    headSha: `sha${number}`,
  };
}

function source(pulls: BotPullRequest[]): ConstructorParameters<typeof BotPrRiskDesk>[0]['source'] {
  return {
    listBotPullRequests: async () => pulls,
    readBotPrDetail: async () => ({ body: null, files: [] }),
    readReleaseNotes: async () => null,
  };
}

function noErrors(): ErrorRecorder {
  return { record: () => ({}) as ReturnType<ErrorRecorder['record']> } as unknown as ErrorRecorder;
}
