import type { PetRarity, PetSpecies, PetStage } from '../types.js';

/**
 * The pixel grids, and the only place in the codebase that knows what a species
 * looks like.
 *
 * The wire carries `species`, `stage` and `seed`; what those *draw as* is a
 * cockpit fact, and a server that also knew would be a second place to change the
 * day a sprite changes.
 *
 * One exported const per group rather than one per creature, because knip runs
 * every rule at `error` and nine separately-exported grids would read as nine
 * unimported symbols.
 *
 * Characters, uniform across every grid:
 *   `.` nothing   `o` outline   `O` body   `h` highlight   `e` eye   `m` marking
 *
 * Rows are padded to the widest at draw time, so a grid that is ragged in the
 * source is still square on the canvas — the alternative is counting dots.
 */

/**
 * Every species in a rarity tier shares one hatchling.
 *
 * This began as an art saving — four grids instead of nine — and turned out to be
 * the better mechanic: a hatchling is a thing you are *waiting to find out about*,
 * and the reveal at the juvenile stage is worth more than the five sprites it
 * costs. The tier still shows through, so a mythic egg is recognisably a prize
 * before it is anything else.
 */
const HATCHLINGS: Record<PetRarity, readonly string[]> = {
  common: ['..oooo..', '.oOOOOo.', 'oOhOOhOo', 'oOeOOeOo', 'oOOOOOOo', 'oOOmmOOo', '.oOOOOo.', '..oooo..'],
  uncommon: ['..o..o..', '..oooo..', '.oOhhOo.', 'oOOOOOOo', 'oOeOOeOo', 'oOOOOOOo', '.oOmmOo.', '..oooo..'],
  rare: ['...oo...', '..oOOo..', '.oOhhOo.', 'oOOOOOOo', 'oOeOOeOo', 'oOmOOmOo', '.oOOOOo.', '..oooo..'],
  mythic: ['.o.oo.o.', '.oooooo.', 'oOhOOhOo', 'oOOOOOOo', 'oOeOOeOo', 'oOmmmmOo', 'oOOOOOOo', '.oooooo.'],
};

/** The juvenile is the first form that says what you have. */
const JUVENILES: Record<PetSpecies, readonly string[]> = {
  pip: [
    '...ooooo...',
    '..oOOOOOo..',
    '.oOhOOOhOo.',
    'oOOeOOOeOOo',
    'oOOOOOOOOOo',
    'oOOOmmmOOOo',
    '.oOOOOOOOo.',
    '..oOOOOOo..',
    '...ooooo...',
    '...o...o...',
    '...o...o...',
  ],
  nib: [
    '.....o.....',
    '....ooo....',
    '...oOOOo...',
    '..oOhOhOo..',
    '.oOOeOeOOo.',
    'oOOOOOOOOOo',
    'oOOOmmmOOOo',
    '.oOOOOOOOo.',
    '..oOOOOOo..',
    '...ooooo...',
    '...o...o...',
  ],
  tuft: [
    '..o.....o..',
    '.oOo...oOo.',
    '.oOOoooOOo.',
    'oOhOOOOOhOo',
    'oOeOOOOOeOo',
    'oOOOOOOOOOo',
    'oOOmmmmmOOo',
    '.oOOOOOOOo.',
    '..oOOOOOo..',
    '...ooooo...',
    '..o.....o..',
  ],
  warden: [
    '..oo...oo..',
    '.oOOo.oOOo.',
    '.oOOOoOOOo.',
    'oOhOOOOOhOo',
    'oOeOOOOOeOo',
    'oOOOmmmOOOo',
    'oOOOOOOOOOo',
    'oOOOOOOOOOo',
    '.oOOOOOOOo.',
    '..ooooooo..',
    '..o.....o..',
  ],
  cinder: [
    '....o.o....',
    '...oOoOo...',
    '..oOOOOOo..',
    '.oOhOOOhOo.',
    'oOOeOOOeOOo',
    'oOOOOOOOOOo',
    'oOmmOmOmmOo',
    '.oOOOOOOOo.',
    '..oOOOOOo..',
    '...ooooo...',
    '...o...o...',
  ],
  nocturne: [
    '..o.....o..',
    '..oo...oo..',
    '.moOooooOm.',
    'oOOOOOOOOOo',
    'oOeeOOOeeOo',
    'oOeeOOOeeOo',
    'oOOOOOOOOOo',
    '.oOmOOOmOo.',
    '..oOOOOOo..',
    '...ooooo...',
    '..o.....o..',
  ],
  lander: [
    '..ooooooo..',
    '.oOOOOOOOo.',
    'oOhOOOOOhOo',
    'oOeOOOOOeOo',
    'oOOOOOOOOOo',
    'oOmmmmmmmOo',
    'oOOOOOOOOOo',
    'oOOOOOOOOOo',
    '.oOOOOOOOo.',
    '.ooooooooo.',
    '.o.o...o.o.',
  ],
  quill: [
    '....mmm....',
    '...ommmo...',
    '..oOmmmOo..',
    '.oOhOOOhOo.',
    'oOOeOOOeOOo',
    'oOOOOOOOOOo',
    'oOOOmmmOOOo',
    '.oOOOOOOOo.',
    '..oOOOOOo..',
    '...ooooo...',
    '...o...o...',
  ],
  ouroboros: [
    '...ooooo...',
    '..oOOOOOo..',
    '.oOmmmmmOo.',
    'oOmOOOOOmOo',
    'oOmOeOeOmOo',
    'oOmOOOOOmOo',
    'oOmmmOmmmOo',
    '.oOOOOOOOo.',
    '..oOOOOOo..',
    '...ooooo...',
    '..o..o..o..',
  ],
  mote: [
    '...........',
    '.....o.....',
    '....ooo....',
    '...oOhOo...',
    '..oOeOeOo..',
    '..oOOOOOo..',
    '..oOmmmOo..',
    '...oOOOo...',
    '....ooo....',
    '...........',
    '...........',
  ],
  beck: [
    '.....m.....',
    '....ooo....',
    '...oOOOo...',
    '..oOhOhOo..',
    '.oOOeOeOOo.',
    'oOOOOOOOOOo',
    'oOOOmmmOOOo',
    '.ooooooooo.',
    '...o...o...',
    '....mmm....',
    '...........',
  ],
  berth: [
    '...........',
    '....ooo....',
    '...oOhOo...',
    '..oOeOeOo..',
    '.oOOOOOOOo.',
    'oOOOmmmOOOo',
    'oOOOOOOOOOo',
    'ommooooommo',
    'om.......mo',
    'ommmmmmmmmo',
    '...........',
  ],
  stoke: [
    '.....m.....',
    '....m.m....',
    '...ooooo...',
    '..oOhOhOo..',
    '.oOeOOOeOo.',
    'oOOOOOOOOOo',
    'oOOmmmmmOOo',
    '.oOOOOOOOo.',
    '..ooooooo..',
    '...o...o...',
    '...........',
  ],
  speck: [
    '...........',
    '...m...m...',
    '....ooo....',
    '...oOhOo...',
    '..oOeOeOo..',
    '..oOOOOOo..',
    '...oOmOo...',
    '....ooo....',
    '.....o.....',
    '....m.m....',
    '...........',
  ],
  patch: [
    'ooooooooooo',
    'oOhOOOOOhOo',
    'oOeOOOOOeOo',
    'oOOOOOOOOOo',
    'oOmOmOmOmOo',
    'oOOOOOOOOOo',
    'oOmOmOmOmOo',
    'oOOOOOOOOOo',
    'ooooooooooo',
    '.m.......m.',
    '...........',
  ],
  chit: [
    '...........',
    '.ooooooooo.',
    '.oOhOOOhOo.',
    '.oOeOOOeOo.',
    '.oOOOOOOOo.',
    '.oOmmmmmOo.',
    '.oOOOOOOOo.',
    '.oOmmmmmOo.',
    '.ooooooooo.',
    '...o...o...',
    '...........',
  ],
  vellum: [
    '...........',
    'ooooooooooo',
    'oOhOOOOOhOo',
    'oOeOOOOOeOo',
    'oOmmmmmmmOo',
    'oOOOOOOOOOo',
    'oOmmmmmmmOo',
    'oOOOOOOOOOo',
    'ooooooooooo',
    '..o.....o..',
    '...........',
  ],
  drift: [
    '...mmmmm...',
    '..mOOOOOm..',
    '.mOOOOOOOm.',
    '..m.....m..',
    '...m...m...',
    '....ooo....',
    '...oOhOo...',
    '..oOeOeOo..',
    '..oOmmmOo..',
    '...ooooo...',
    '...........',
  ],
  bramble: [
    '.m.......m.',
    '..m.....m..',
    '..ooooooo..',
    '.oOhOOOhOo.',
    'moOeOOOeOom',
    '.oOOOOOOOo.',
    '.oOmmmmmOo.',
    '..ooooooo..',
    '.m..o.o..m.',
    '....o.o....',
    '...........',
  ],
  cairn: [
    '....mmm....',
    '...ooooo...',
    '..oOhOhOo..',
    '..oOeOeOo..',
    '.ooooooooo.',
    'oOOOOOOOOOo',
    'oOmmmmmmmOo',
    'ooooooooooo',
    'oOOOOOOOOOo',
    'ooooooooooo',
    '...........',
  ],
  ingot: [
    '...........',
    '..ooooooo..',
    '.oOhOOOhOo.',
    'oOOeOOOeOOo',
    'oOOOOOOOOOo',
    'oOmmmmmmmOo',
    'oOOOOOOOOOo',
    '.ooooooooo.',
    '..ooooooo..',
    '..o.....o..',
    '..o.....o..',
  ],
  clarion: [
    'oo.......oo',
    '.oo.....oo.',
    '..ooooooo..',
    '.oOhOOOhOo.',
    'oOOeOOOeOOo',
    'oOmOOOOOmOo',
    'oOmmmmmmmOo',
    '.oOOOOOOOo.',
    '..ooooooo..',
    '..o.....o..',
    '..o.....o..',
  ],
  covenant: [
    '..o.....o..',
    '.ooo...ooo.',
    '.oOo...oOo.',
    '..ooooooo..',
    '.oOhOOOhOo.',
    'oOOeOOOeOOo',
    'oOOmmmmmOOo',
    'oOmOOOOOmOo',
    '.oOmmmmmOo.',
    '..ooooooo..',
    '..o.....o..',
  ],
  oracle: [
    '...ooooo...',
    '..oOOOOOo..',
    '.oOhOeOhOo.',
    'oOOOOOOOOOo',
    'oOeOOOOOeOo',
    'oOOOOOOOOOo',
    'oOmmmOmmmOo',
    '.oOOmOmOOo.',
    '..ooooooo..',
    '..o.....o..',
    '..o.....o..',
  ],
  keystone: [
    'ooooooooooo',
    'oOhOOOOOhOo',
    'oOeOOOOOeOo',
    'oOOOOOOOOOo',
    '.oOmmmmmOo.',
    '.oOOOOOOOo.',
    '..oOmmmOo..',
    '..oOOOOOo..',
    '...ooooo...',
    '...o...o...',
    '...o...o...',
  ],
  forge: [
    '...m...m...',
    '..mmm.mmm..',
    '.ooooooooo.',
    'oOhOOOOOhOo',
    'oOeOOOOOeOo',
    'oOmmmmmmmOo',
    '.oOOOOOOOo.',
    '..oOOOOOo..',
    '...ooooo...',
    '..ooooooo..',
    '..o.....o..',
  ],
  lodestone: [
    '.oo.....oo.',
    '.oOo...oOo.',
    '.oOoooooOo.',
    '.oOhOOOhOo.',
    'oOOeOOOeOOo',
    'oOOOOOOOOOo',
    'oOmmmOmmmOo',
    'oOOOmOmOOOo',
    '.oOOmmmOOo.',
    '..ooooooo..',
    '..o.....o..',
  ],
};

/** The adult: the same animal, bigger, with whatever it grew. */
const ADULTS: Record<PetSpecies, readonly string[]> = {
  pip: [
    '....oooooo....',
    '..ooOOOOOOoo..',
    '.oOOOOOOOOOOo.',
    'oOOhOOOOOOhOOo',
    'oOOeOOOOOOeOOo',
    'oOOOOOOOOOOOOo',
    'oOOOOmmmmOOOOo',
    'oOOOOOOOOOOOOo',
    '.oOOOOOOOOOOo.',
    '..oOOOOOOOOo..',
    '...oooooooo...',
    '...o......o...',
    '...o......o...',
    '..oo......oo..',
  ],
  nib: [
    '......oo......',
    '.....oOOo.....',
    '....oOOOOo....',
    '...oOhOOhOo...',
    '..oOOeOOeOOo..',
    '.oOOOOOOOOOOo.',
    'oOOOOmmmmOOOOo',
    'oOOOOOOOOOOOOo',
    'oOOOOOOOOOOOOo',
    '.oOOOOOOOOOOo.',
    '..oOOOOOOOOo..',
    '...oooooooo...',
    '...o......o...',
    '..oo......oo..',
  ],
  tuft: [
    '..oo......oo..',
    '.oOOo....oOOo.',
    '.oOOOooooOOOo.',
    'oOOhOOOOOOhOOo',
    'oOOeOOOOOOeOOo',
    'oOOOOOOOOOOOOo',
    'oOmmmmmmmmmmOo',
    'oOOmmmmmmmmOOo',
    '.oOOOOOOOOOOo.',
    '..oOOOOOOOOo..',
    '...oooooooo...',
    '..o..o..o..o..',
    '..o..o..o..o..',
    '..oo.oo.oo.oo.',
  ],
  warden: [
    '..ooo....ooo..',
    '.oOOOo..oOOOo.',
    '.oOOOOooOOOOo.',
    'oOOOOOOOOOOOOo',
    'oOOhOOOOOOhOOo',
    'oOOeOOOOOOeOOo',
    'oOOOOmmmmOOOOo',
    'oOOOOOOOOOOOOo',
    'oOOOOOOOOOOOOo',
    'oOOOOOOOOOOOOo',
    '.oOOOOOOOOOOo.',
    '..oooooooooo..',
    '..o........o..',
    '.oo........oo.',
  ],
  cinder: [
    '.....o..o.....',
    '....oOooOo....',
    '...oOOOOOOo...',
    '..oOOOOOOOOo..',
    '.oOhOOOOOOhOo.',
    'oOOeOOOOOOeOOo',
    'oOOOOOOOOOOOOo',
    'oOmmOOmmOOmmOo',
    'oOOmmOmmOmmOOo',
    '.oOOOOOOOOOOo.',
    '..oOOOOOOOOo..',
    '...oooooooo...',
    '...o......o...',
    '..oo......oo..',
  ],
  nocturne: [
    '..oo......oo..',
    '.oOOo....oOOo.',
    'moOOOooooOOOom',
    'oOOOOOOOOOOOOo',
    'oOeeOOOOOOeeOo',
    'oOeeOOOOOOeeOo',
    'oOOOOOOOOOOOOo',
    'oOOmOOmmOOmOOo',
    'oOOOmmOOmmOOOo',
    '.oOOOOOOOOOOo.',
    '..oOOOOOOOOo..',
    '...oooooooo...',
    '..o........o..',
    '.oo........oo.',
  ],
  lander: [
    '.oooooooooooo.',
    'oOOOOOOOOOOOOo',
    'oOhOOOOOOOOhOo',
    'oOeOOOOOOOOeOo',
    'oOOOOOOOOOOOOo',
    'oOmmmmmmmmmmOo',
    'oOOOOOOOOOOOOo',
    'oOmmmmmmmmmmOo',
    'oOOOOOOOOOOOOo',
    'oOOOOOOOOOOOOo',
    '.oOOOOOOOOOOo.',
    '.oooooooooooo.',
    '.o.oo....oo.o.',
    '.oo.o....o.oo.',
  ],
  quill: [
    '.....mmmm.....',
    '....mmmmmm....',
    '...ommmmmmo...',
    '..oOmmmmmmOo..',
    '.oOhOmmmmOhOo.',
    'oOOeOOOOOOeOOo',
    'oOOOOOOOOOOOOo',
    'oOOOOmmmmOOOOo',
    'oOOOOOOOOOOOOo',
    '.oOOOOOOOOOOo.',
    '..oOOOOOOOOo..',
    '...oooooooo...',
    '...o......o...',
    '..oo......oo..',
  ],
  ouroboros: [
    '...oooooooo...',
    '..oOOOOOOOOo..',
    '.oOmmmmmmmmOo.',
    'oOmmOOOOOOmmOo',
    'oOmOOOOOOOOmOo',
    'oOmOOeOOeOOmOo',
    'oOmOOOOOOOOmOo',
    'oOmmOOmmOOmmOo',
    'oOOmmmmmmmmOOo',
    '.oOOOOOOOOOOo.',
    '..oOOOOOOOOo..',
    '...oooooooo...',
    '..o..o..o..o..',
    '..oo.oo.oo.oo.',
  ],
  mote: [
    '......oo......',
    '.....oOOo.....',
    '....oOhhOo....',
    '...oOOOOOOo...',
    '..oOOeOOeOOo..',
    '..oOOOOOOOOo..',
    '..oOOmmmmOOo..',
    '..oOOOOOOOOo..',
    '...oOOOOOOo...',
    '....oOOOOo....',
    '.....oooo.....',
    '.....o..o.....',
    '....oo..oo....',
    '..............',
  ],
  beck: [
    '......mm......',
    '.....oooo.....',
    '....oOOOOo....',
    '...oOhOOhOo...',
    '..oOOeOOeOOo..',
    '.oOOOOOOOOOOo.',
    'oOOOOmmmmOOOOo',
    'oOOOOOOOOOOOOo',
    '.oooooooooooo.',
    '..o........o..',
    '..o........o..',
    '....mmmmmm....',
    '..............',
    '..............',
  ],
  berth: [
    '..............',
    '.....oooo.....',
    '....oOhhOo....',
    '...oOeOOeOo...',
    '..oOOOOOOOOo..',
    '.oOOOmmmmOOOo.',
    'oOOOOOOOOOOOOo',
    'oOOOOOOOOOOOOo',
    'ommoooooooommo',
    'om..........mo',
    'om..........mo',
    'ommmmmmmmmmmmo',
    '..............',
    '..............',
  ],
  stoke: [
    '......mm......',
    '.....m..m.....',
    '....m....m....',
    '...oooooooo...',
    '..oOOhOOhOOo..',
    '.oOOeOOOOeOOo.',
    'oOOOOOOOOOOOOo',
    'oOOOmmmmmmOOOo',
    'oOOOOOOOOOOOOo',
    '.oOOOOOOOOOOo.',
    '..oooooooooo..',
    '...o......o...',
    '..oo......oo..',
    '..............',
  ],
  speck: [
    '..............',
    '...m......m...',
    '.....oooo.....',
    '....oOhhOo....',
    '...oOeOOeOo...',
    '..oOOOOOOOOo..',
    '..oOOOmmOOOo..',
    '...oOOOOOOo...',
    '....oOOOOo....',
    '.....oooo.....',
    '......oo......',
    '.....m..m.....',
    '..............',
    '..............',
  ],
  patch: [
    'oooooooooooooo',
    'oOhOOOOOOOOhOo',
    'oOeOOOOOOOOeOo',
    'oOOOOOOOOOOOOo',
    'oOmOmOmOmOmOOo',
    'oOOOOOOOOOOOOo',
    'oOmOmOmOmOmOOo',
    'oOOOOOOOOOOOOo',
    'oOmOmOmOmOmOOo',
    'oOOOOOOOOOOOOo',
    'oooooooooooooo',
    '.m..........m.',
    '..............',
    '..............',
  ],
  chit: [
    '..............',
    '.oooooooooooo.',
    '.oOhOOOOOOhOo.',
    '.oOeOOOOOOeOo.',
    '.oOOOOOOOOOOo.',
    '.oOmmmmmmmmOo.',
    '.oOOOOOOOOOOo.',
    '.oOmmmmmmmmOo.',
    '.oOOOOOOOOOOo.',
    '.oOmmmmmmmmOo.',
    '.oooooooooooo.',
    '...o......o...',
    '..oo......oo..',
    '..............',
  ],
  vellum: [
    '..............',
    'oooooooooooooo',
    'oOhOOOOOOOOhOo',
    'oOeOOOOOOOOeOo',
    'oOmmmmmmmmmmOo',
    'oOOOOOOOOOOOOo',
    'oOmmmmmmmmmmOo',
    'oOOOOOOOOOOOOo',
    'oOmmmmmmmmmmOo',
    'oOOOOOOOOOOOOo',
    'oooooooooooooo',
    '..o........o..',
    '..oo......oo..',
    '..............',
  ],
  drift: [
    '...mmmmmmmm...',
    '..mOOOOOOOOm..',
    '.mOOOOOOOOOOm.',
    '.m..........m.',
    '..m........m..',
    '...m......m...',
    '....oooooo....',
    '...oOhOOhOo...',
    '..oOOeOOeOOo..',
    '..oOOOOOOOOo..',
    '..oOOmmmmOOo..',
    '...oOOOOOOo...',
    '....oooooo....',
    '..............',
  ],
  bramble: [
    '.m..........m.',
    '..m........m..',
    '...oooooooo...',
    '..oOhOOOOhOo..',
    '.moOeOOOOeOom.',
    '.oOOOOOOOOOOo.',
    'moOOmmmmmmOOom',
    '.oOOOOOOOOOOo.',
    '..oooooooooo..',
    '.m..o....o..m.',
    '....o....o....',
    '...oo....oo...',
    '..............',
    '..............',
  ],
  cairn: [
    '.....mmmm.....',
    '....oooooo....',
    '...oOhOOhOo...',
    '...oOeOOeOo...',
    '..oooooooooo..',
    '.oOOOOOOOOOOo.',
    '.oOmmmmmmmmOo.',
    '.oooooooooooo.',
    'oOOOOOOOOOOOOo',
    'oOmmmmmmmmmmOo',
    'oooooooooooooo',
    'oOOOOOOOOOOOOo',
    'oooooooooooooo',
    '..............',
  ],
  ingot: [
    '..............',
    '...oooooooo...',
    '..oOhOOOOhOo..',
    '.oOOeOOOOeOOo.',
    'oOOOOOOOOOOOOo',
    'oOmmmmmmmmmmOo',
    'oOOOOOOOOOOOOo',
    'oOmmmmmmmmmmOo',
    '.oOOOOOOOOOOo.',
    '..oooooooooo..',
    '...oooooooo...',
    '...o......o...',
    '...o......o...',
    '..oo......oo..',
  ],
  clarion: [
    'oo..........oo',
    '.oo........oo.',
    '..oo......oo..',
    '...oooooooo...',
    '..oOhOOOOhOo..',
    '.oOOeOOOOeOOo.',
    'oOmOOOOOOOOmOo',
    'oOmmOOOOOOmmOo',
    'oOmmmmmmmmmmOo',
    '.oOOOOOOOOOOo.',
    '..oooooooooo..',
    '...o......o...',
    '...o......o...',
    '..oo......oo..',
  ],
  covenant: [
    '...o......o...',
    '..ooo....ooo..',
    '..oOo....oOo..',
    '...oooooooo...',
    '..oOhOOOOhOo..',
    '.oOOeOOOOeOOo.',
    'oOOOmmmmmmOOOo',
    'oOOmOOOOOOmOOo',
    'oOOmOOOOOOmOOo',
    '.oOOmmmmmmOOo.',
    '..oOOOOOOOOo..',
    '...oooooooo...',
    '...o......o...',
    '..oo......oo..',
  ],
  oracle: [
    '....oooooo....',
    '..ooOOOOOOoo..',
    '.oOOhOOeOOhOo.',
    'oOOOOOOOOOOOOo',
    'oOOeOOOOOOeOOo',
    'oOOOOOOOOOOOOo',
    'oOmmmOOOOmmmOo',
    'oOOmmmOOmmmOOo',
    '.oOOmmOOmmOOo.',
    '..oOOOmmOOOo..',
    '...oooooooo...',
    '...o......o...',
    '...o......o...',
    '..oo......oo..',
  ],
  keystone: [
    'oooooooooooooo',
    'oOhOOOOOOOOhOo',
    'oOeOOOOOOOOeOo',
    'oOOOOOOOOOOOOo',
    '.oOmmmmmmmmOo.',
    '.oOOOOOOOOOOo.',
    '..oOmmmmmmOo..',
    '..oOOOOOOOOo..',
    '...oOmmmmOo...',
    '...oOOOOOOo...',
    '....oooooo....',
    '....o....o....',
    '....o....o....',
    '...oo....oo...',
  ],
  forge: [
    '....m....m....',
    '...mmm..mmm...',
    '..mmmmmmmmmm..',
    '.oooooooooooo.',
    'oOhOOOOOOOOhOo',
    'oOeOOOOOOOOeOo',
    'oOmmmmmmmmmmOo',
    'oOOOOOOOOOOOOo',
    '.oOOOOOOOOOOo.',
    '..oOOOOOOOOo..',
    '...oOOOOOOo...',
    '..oooooooooo..',
    '..o........o..',
    '..oo......oo..',
  ],
  lodestone: [
    '..oo......oo..',
    '..oOo....oOo..',
    '..oOo....oOo..',
    '..oOooooooOo..',
    '..oOhOOOOhOo..',
    '.oOOeOOOOeOOo.',
    'oOOOOOOOOOOOOo',
    'oOmmmOOOOmmmOo',
    'oOOmmmOOmmmOOo',
    '.oOOmmmmmmOOo.',
    '..oOOmmmmOOo..',
    '...oooooooo...',
    '...o......o...',
    '..oo......oo..',
  ],
};

/**
 * The shell a drop arrives in, one grid per tier.
 *
 * The tier shows and the species does not, which is the whole shape of the
 * reveal: `mote` and `ouroboros` drop into the same corner of the rail, and only
 * one of them is worth stopping what you are doing for. A shell that gave away
 * nothing would make every egg the same egg; a shell that gave away the animal
 * would leave the click with nothing to say. Markings carry the tier — a common
 * has one speck, a mythic is banded end to end — and the seed's own palette does
 * the rest, so no two eggs of a tier are the same egg either.
 */
const EGGS: Record<PetRarity, readonly string[]> = {
  common: [
    '...oooo...',
    '..oOOOOo..',
    '.oOhhOOOo.',
    '.oOhOOOOo.',
    'oOOOOOOOOo',
    'oOOOOOOOOo',
    'oOOOOmOOOo',
    'oOOOOOOOOo',
    'oOOOOOOOOo',
    'oOOOOOOOOo',
    '.oOOOOOOo.',
    '..oooooo..',
  ],
  uncommon: [
    '...oooo...',
    '..oOOOOo..',
    '.oOhhOOOo.',
    '.oOhOOOOo.',
    'oOOOOOOOOo',
    'oOmmmmmmOo',
    'oOOOOOOOOo',
    'oOOOOOOOOo',
    'oOmmmmmmOo',
    'oOOOOOOOOo',
    '.oOOOOOOo.',
    '..oooooo..',
  ],
  rare: [
    '...oooo...',
    '..oOOOOo..',
    '.oOhhOOOo.',
    '.oOhOOmOo.',
    'oOOOmmOOOo',
    'oOOmOOOOOo',
    'oOmOOOmmOo',
    'oOOOOmOOOo',
    'oOOmmOOOOo',
    'oOOOOOOmOo',
    '.oOOOOOOo.',
    '..oooooo..',
  ],
  mythic: [
    '...oooo...',
    '..oOmmOo..',
    '.oOhmmOOo.',
    '.oOhmmOOo.',
    'oOOmmmOOOo',
    'oOmmOmmmOo',
    'oOmmmOmmOo',
    'oOOmmmmOOo',
    'oOmmOmmmOo',
    'oOOmmmOOOo',
    '.oOmmmOOo.',
    '..oooooo..',
  ],
};

/**
 * How far gone the shell is, drawn over the egg: `c` splits it along the outline
 * ink, `k` takes the pixel out altogether.
 *
 * Three grids rather than a fracture simulation, and indexed by how many times
 * the egg has rocked — the animation is a sequence of *states*, so a run that is
 * interrupted, replayed or arrived at from a reload draws the same shell at the
 * same count rather than wherever a physics clock had got to.
 */
const CRACKS: readonly (readonly string[])[] = [
  [
    '..........',
    '..........',
    '..........',
    '..........',
    '.....c....',
    '....c.....',
    '.....c....',
    '..........',
    '..........',
    '..........',
    '..........',
    '..........',
  ],
  [
    '..........',
    '..........',
    '...c......',
    '...c......',
    '..c.c.....',
    '...c......',
    '....c.....',
    '...c......',
    '..c.......',
    '..........',
    '..........',
    '..........',
  ],
  [
    '..........',
    '..........',
    '...c......',
    '...c......',
    '..c.c.....',
    '.ckckckck.',
    '..cc.cc...',
    '...c......',
    '..c.......',
    '..........',
    '..........',
    '..........',
  ],
];

/**
 * The crack overlay after `rocks` rocks, or null before the first one.
 *
 * Clamped rather than indexed blind: the caller counts rocks, and a count that
 * runs past the last grid should draw the most broken shell there is instead of
 * an undefined one.
 */
export function crackFor(rocks: number): readonly string[] | null {
  if (rocks <= 0) return null;
  return CRACKS[Math.min(rocks, CRACKS.length) - 1]!;
}

/**
 * The grid for one form.
 *
 * `'egg'` rides beside the three stages rather than in `PetStage`, because a stage
 * is what `fed` bought and a shell is what nobody has opened yet — two different
 * facts, and the domain type answers the first. Both of the first two forms ignore
 * `species` entirely, which is the catalogue's whole shape: the tier is what an
 * egg and a hatchling say, and the juvenile is the first form that names an
 * animal.
 */
export function spriteFor(species: PetSpecies, rarity: PetRarity, stage: PetStage | 'egg'): readonly string[] {
  if (stage === 'egg') return EGGS[rarity]!;
  if (stage === 'hatchling') return HATCHLINGS[rarity]!;
  return stage === 'juvenile' ? JUVENILES[species]! : ADULTS[species]!;
}
