import { dispatchVerdict } from '../dispatchCooldown.js';
import { featureSequenceOrigin } from '../../sequence/sequence.js';
import type { RawAction, StageContext } from './context.js';

/**
 * Propose the order the stories under a Feature should be worked in, when the set
 * of stories has changed since anybody wrote one.
 *
 * `feature-summary`'s shape throughout, deliberately, because that rule already
 * solved this one's hard parts: a desk agent with no branch and no worktree,
 * triggered by a standing-key comparison rather than by an event, ranked at the
 * bottom of the pipeline, failing open and silent. Two things differ.
 *
 * **The key is membership, not movement.** `featureSequenceKey` digests which
 * stories are under the Feature and what the provider says about them — never how
 * they are going. A story merging does not invalidate an order; a story being
 * _added_ does. The summary's key is standings for exactly the opposite reason, and
 * re-proposing an order every time a child landed would ask an operator to
 * re-accept the same sequence eight times.
 *
 * **A `declined` order is an answer and holds this rule off.** It is stored against
 * the key it declined, so "run them all" stands until the set of stories changes —
 * a proposal that came back on the next pulse would make the fleet argue with the
 * operator once a Feature until they gave in.
 *
 * Ranked below every other rule beside `feature-summary`, and for its reason: it
 * produces no work, so nothing may wait behind it. Fails open and silent — a
 * sequencer that crashed or spent its cap leaves every story eligible in exactly
 * the order it has today, and there is no escalation, because an inbox item per
 * unsequenced Feature would be a queue of chores generated by a feature nobody
 * asked for.
 */
export function featureSequence(s: StageContext): void {
  const { ctx } = s;
  for (const feature of s.sequenceableFeatures) {
    const stored = s.sequences.get(`issue:${feature.feature.number}`);
    // The whole gate, at the cost of one string comparison per Feature per pulse:
    // an order written against this set of stories exists, whatever the operator
    // then said about it, so there is nothing to ask.
    if (stored?.standingKey === feature.key) continue;
    const origin = featureSequenceOrigin(feature.feature.number);
    // A sequencer already on this Feature is writing against the membership it
    // will be stamped with, so a second one dispatched for the same change would
    // write the same order twice and pay for it twice.
    if (s.activeOrigins.has(origin)) continue;

    const verdict = dispatchVerdict(origin, s.now, ctx.recentDecisions, s.cooldown);
    if (verdict.kind === 'escalate' || verdict.kind === 'hold') continue;

    const title = `Sequence feature #${feature.feature.number}`;
    const reason = stored
      ? `Feature #${feature.feature.number} has gained or lost stories since its order was written.`
      : `Feature #${feature.feature.number} has ${feature.children.length} stories and no order.`;
    s.candidates.push({
      origin,
      rule: 'feature-sequence',
      title,
      kind: 'desk',
      // No branch and no worktree, `feature-summary`'s reason: it writes no files,
      // and a checkout would only be a temptation to start work on somebody's story.
      branch: null,
      reason,
      held: verdict.kind === 'cooldown' ? 'cooldown' : undefined,
      action: {
        type: 'dispatch_desk_agent',
        title,
        prompt: s.templates.render('feature-sequence', {
          number: feature.feature.number,
          title: feature.feature.title,
        }),
        originRef: origin,
        originTitle: feature.feature.title,
        rule: 'feature-sequence',
        reason,
      } satisfies RawAction,
    });
  }
}
