import type { ConfigField } from './configFields.js';

export const FLEET_FIELDS: readonly ConfigField[] = [
  {
    path: 'heartbeatIntervalMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'Gap between timer-driven cycles.',
  },
  {
    path: 'idleHeartbeatIntervalMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'Gap between cycles while nothing is moving — no live agent, no queued work, no build in flight. Never shorter than the heartbeat itself.',
  },
  {
    path: 'hotReadMaxAgeMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How long a per-entity reading is reused for something that is moving (a build in flight, an open dispatch, merge-readiness in flux) when nothing on the cheap list payload says it changed.',
  },
  {
    path: 'coldReadMaxAgeMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'The same, for everything else. A cold item is still listed and still in the world every pulse; it just is not re-hydrated more often than this. The main lever on what a fast pulse costs the provider.',
  },
  {
    path: 'maxConcurrentAgents',
    type: 'number',
    access: 'plain',
    why: 'Hard cap on concurrently-running agents. Seeds the live cap, which a restart reverts to.',
  },
  {
    path: 'startPaused',
    type: 'boolean',
    access: 'plain',
    why: 'Boot with dispatch paused. Live pause/resume is ephemeral and separate.',
  },
  {
    path: 'sendPrRepliesWithoutApproval',
    type: 'boolean',
    access: 'plain',
    why: 'Send a reply an agent drafted straight to the review thread, without asking you. On by default — it is prose the fleet wrote, on a thread you do not control, signed as the harness. Turn it off to be asked instead: every draft then waits in your inbox as a proposal. Replies only; a merge is still authorized per pull request by landing a stack.',
  },
  {
    path: 'closedPrWindowMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How far back a provider looks for pull requests that have left the open set.',
  },
  {
    path: 'closedPrCatchUpMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'The furthest back a read may reach to catch up on closes it missed while the harness was down. The window above is the ordinary reach; this is the cap on the extra.',
  },
  {
    path: 'obstacleDormantMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How long an obstacle nobody re-reports and nothing owns stays on the board before it goes dormant. Its keys survive, so a re-report reopens it rather than filing a second one.',
  },
  {
    path: 'obstacleTicketApproval',
    type: 'boolean',
    access: 'plain',
    why: 'Whether a bug the fleet wants filed for an obstacle waits for your approval on the Obstacles tab. On, the harness proposes and you decide; off, the pulse files it itself. Either way the row stays standing and keeps every way out that is not a person.',
  },
  {
    path: 'environments',
    type: 'json',
    access: 'fileOnly',
    why: 'Where landed work travels, and the command that says whether a commit has got there.',
  },
  {
    path: 'environmentProbeIntervalMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How often an unconfirmed landing is asked about again — and the precision of every “arrived at”.',
  },
  {
    path: 'environmentHealthIntervalMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How often each environment’s own health check is asked whether it is well.',
  },
  {
    path: 'watchIntervalMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How often an open post-deploy watch asks its environment again. Nothing is asked when none is open.',
  },
  {
    path: 'remoteValidation.tenantTimeoutMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How long an ensureTenant or reseed command may take before it is killed. Provisioning a tenant is a job of tens of minutes by the spec’s own account, so the thirty seconds every other command gets would kill both of them on every invocation.',
  },
  {
    path: 'remoteValidation.scriptGraceMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How long a one-off validation script’s source is kept past the goal’s delivery before the sweep removes it. A one-off that outlives its goal is an unreviewed test nobody maintains and nobody can attribute, failing against a product that moved on — a second suite grown by accident.',
  },
  {
    path: 'upNextOverrideTtlMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How long an operator’s Up next override outranks the dispatcher’s own order.',
  },

  {
    path: 'agentMode',
    type: 'enum',
    options: ['stream', 'raw'],
    access: 'plain',
    why: 'How agents are launched. The runtime object is picked once, at boot.',
  },
  {
    path: 'agentPermissionMode',
    type: 'string',
    access: 'plain',
    why: 'Permission posture handed to each agent. `bypassPermissions` is refused under root.',
  },
  {
    path: 'agentModels',
    type: 'json',
    access: 'plain',
    why: 'Which model each rule and each pinned profile dispatches on.',
  },
  {
    path: 'agentAllowedTools',
    type: 'stringList',
    access: 'plain',
    why: 'Tools an agent may use without asking. Rides in --settings, not --allowedTools.',
  },
  {
    path: 'agentPromptDelayMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'Wait before the prompt is delivered.',
  },
  {
    path: 'agentSubmitDelayMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'Gap between a terminal message and the carriage return that submits it.',
  },
  {
    path: 'agentWaitingPatterns',
    type: 'stringList',
    access: 'plain',
    why: 'Extra output patterns that mean an agent is waiting on a person.',
  },
  {
    path: 'agentStallNudges',
    type: 'number',
    access: 'plain',
    why: 'Nudges a stalled agent gets before it is given up on.',
  },
  {
    path: 'agentStallParkMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How long a stalled agent waits on you before the harness marks it done.',
  },
  {
    path: 'agentStallExtendMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How much one press of Extend adds to that countdown.',
  },
  {
    path: 'agentSilenceParkMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How long an agent may produce nothing at all before it is read as wedged.',
  },
  {
    path: 'agentResumeAttempts',
    type: 'number',
    access: 'plain',
    why: 'How many times a mid-run crash is re-attached before the run is failed.',
  },
  {
    path: 'mcpArgsRetentionDays',
    type: 'number',
    access: 'plain',
    why: 'How long a recorded MCP call keeps its arguments, in days. The call itself is kept for ever — only the arguments go. 0 records none at all.',
  },
  {
    path: 'whitelistedApprovals',
    type: 'json',
    access: 'fileOnly',
    why: 'Prompt substrings the harness may answer on your behalf. Written deliberately, in the file.',
  },
  {
    path: 'reviewAreas',
    type: 'json',
    access: 'fileOnly',
    why: 'Which part of the code a review thread was about, worked out from the file it is anchored to. Each row is an area name and a regular expression over the repository-relative path; a path may match several, and one matching nothing leaves the thread in no area at all.',
  },
  {
    path: 'claudeCommand',
    type: 'string',
    access: 'advanced',
    why: 'The agent binary to launch.',
  },
  {
    path: 'claudeArgs',
    type: 'stringList',
    access: 'advanced',
    why: 'Extra arguments, appended last — an --allowedTools here silently drops the harness’s MCP grants.',
  },
];
