import type { ConfigField } from './configFields.js';

export const POLICY_FIELDS: readonly ConfigField[] = [
  {
    path: 'featureBoard',
    type: 'boolean',
    access: 'plain',
    why: 'Let rule `feature-summary` spend one desk agent per Feature whose work has moved, to write down where it has got to — the prose on the Features tab. The tab itself is drawn without it wherever the tracker has a container hierarchy. Turned on, every Feature is summarised once straight away.',
  },
  {
    path: 'planning.maxConcurrentPartsPerIssue',
    type: 'number',
    access: 'plain',
    why: 'How many parts of one plan may have agents at once.',
  },
  {
    path: 'planning.gitFetchIntervalMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'Minimum gap between the fetches plan reconciliation runs before reading branch reality.',
  },
  {
    path: 'planning.fileBudget',
    type: 'number',
    access: 'plain',
    why: 'Changed files past which a pull request is asked whether it is one piece of work or several — the number the planner and every code agent are told to build under, and the trigger for rule `pr-split`. Judgement, not a limit: the assessment is a model’s reading of the diff and a wide-but-coherent change is left alone. 0 turns both off.',
  },
  {
    path: 'validation.checkSets',
    type: 'boolean',
    access: 'plain',
    why: 'Whether the fleet writes a validation check set for a goal it has delivered and puts it to you for approval. Off, no goal grows a set it did not already have, and nothing is proposed — the bench, the hand-over, the desktop channel and a plan-time set are untouched, which is what makes it safe to leave off. It gates authoring and never reading, and it is off by default while what the approval card is asking an operator to accept is still being worked out.',
  },
  {
    path: 'validation.desktopClaimMinutes',
    type: 'number',
    access: 'plain',
    why: 'How long a claimed validation check is held before it is offered again.',
  },
  {
    path: 'ejection.enabled',
    type: 'boolean',
    access: 'plain',
    why: 'Whether an operator can take a running agent’s work into their own Claude Code. Off, no Eject is offered and the route refuses; a hold already standing is still honoured and settleable.',
  },
  {
    path: 'ejection.expiryHours',
    type: 'number',
    access: 'plain',
    why: 'How long an ejection holds its goal and its worktree slot before the harness takes the work back and says so. 0 means no expiry, which is the operator accepting the wedge a hold nobody settles can cause.',
  },
  {
    path: 'ejection.contactGraceMinutes',
    type: 'number',
    access: 'advanced',
    why: 'How long an ejection nobody has contacted the harness about reads as a fresh hold before its card says so and re-offers the link.',
  },
  {
    path: 'review.enabled',
    type: 'boolean',
    access: 'plain',
    why: 'Have the fleet review a pull request of its own before a person is asked to.',
  },
  {
    path: 'review.blocking',
    type: 'boolean',
    access: 'plain',
    why: 'Hold an unreviewed pull request out of the merge gate. Off records the verdict and gates nothing.',
  },
  {
    path: 'review.publish',
    type: 'enum',
    options: ['none', 'comment', 'tooling'],
    access: 'plain',
    why: 'Where the findings go: "none" keeps them to the harness, "comment" has the reviewer post them itself, "tooling" leaves the pull request to the project\u2019s own review tooling and has the reviewer add nothing beside it.',
  },
  {
    path: 'review.publishedThreadProperty',
    type: 'string',
    access: 'plain',
    why: 'The thread property your review tooling stamps its own threads with. Set it, and findings read as dealt with once every stamped thread is resolved — the way a deployment that publishes findings itself, rather than through the reviewer agent, gets its mark back to green. Azure DevOps only; GitHub carries no thread properties.',
  },
  {
    path: 'review.machineAuthors',
    type: 'stringList',
    access: 'fileOnly',
    why: 'Author names that are machines, as regular expressions over the login the provider reports. The third and last source, for a poster neither of the others can see: a service account on a personal access token, a review bot commenting under an ordinary user. Belongs beside publishedThreadProperty in lubbdubb.project.json — which machines comment on a repository is a fact about that repository.',
  },
  {
    path: 'review.publishedThreadRole',
    type: 'string',
    access: 'plain',
    why: 'Which stamped threads count — the value required on “<property>.role”. Empty takes every stamped thread, which on a poster that also opens an unresolvable summary thread never reads as dealt with.',
  },
  {
    path: 'review.modes',
    type: 'json',
    access: 'plain',
    why: 'The ways this project reviews — a charter and a profile each. Two or more switches the triage on.',
  },
  {
    path: 'review.defaultMode',
    type: 'string',
    access: 'plain',
    why: 'The mode a review falls back to when the triage could not answer. Name the thorough one.',
  },
  {
    path: 'review.routingCharterFile',
    type: 'string',
    access: 'plain',
    why: 'A file in the repository saying how to choose between the modes, read by the triage agent.',
  },
  {
    path: 'localRun.instruction',
    type: 'text',
    access: 'plain',
    why: 'How this project’s application is started on your machine. Empty means nothing is startable.',
  },
  {
    path: 'localRun.stopInstruction',
    type: 'text',
    access: 'plain',
    why: 'How it is stopped again. Empty means a stop kills the session but not what it started.',
  },
  {
    path: 'localRun.resumeInstruction',
    type: 'text',
    access: 'plain',
    why: 'How an environment the harness was holding is brought back after a restart. Empty means it is not.',
  },
  {
    path: 'localRun.resumeWindowMs',
    type: 'number',
    access: 'plain',
    why: 'How long after the harness went down a run may still be brought back. 0 means no bound.',
  },
  {
    path: 'localRun.refreshInstruction',
    type: 'text',
    access: 'plain',
    why: 'What a running environment does to pick up new code once its checkout has moved — rebuild, migrate, restart. Empty means it is only told what moved.',
  },
  {
    path: 'localRun.url',
    type: 'string',
    access: 'plain',
    why: 'Where the application lands once it is up, drawn as a link beside the run.',
  },
  {
    path: 'localValidation.instruction',
    type: 'text',
    access: 'plain',
    why: 'What a validating agent is told about reaching your environment — which URL is which, how to sign in, what to leave alone. Never a secret: it is readable here and a project layer commits it.',
  },
  {
    path: 'localValidation.browser',
    type: 'json',
    access: 'plain',
    why: 'The MCP server that gives a validating agent a browser — {command, args}, with {outputDir} and {profileDir} filled in per run. One block, read by both the local validation and a remote validation sheet’s own run. null runs validations without one, and steps that need a screen are reported blocked.',
  },
  {
    path: 'validation.desktopSocketPath',
    type: 'string',
    access: 'advanced',
    why: 'Where the desktop channel binds.',
  },
  {
    path: 'validation.desktopCredentialPath',
    type: 'string',
    access: 'advanced',
    why: 'Where the desktop channel’s minted token is written.',
  },
  {
    path: 'spendBurn.enabled',
    type: 'boolean',
    access: 'plain',
    why: 'Watch a run going past what its kind of work usually costs, steps or takes.',
  },
  {
    path: 'spendBurn.multiple',
    type: 'number',
    access: 'plain',
    why: 'How many times the typical cost counts as burning. Must be above 1.',
  },
  {
    path: 'spendBurn.minimumRuns',
    type: 'number',
    access: 'plain',
    why: 'How many comparable runs are needed before the watch has an opinion.',
  },
  { path: 'spendBurn.floorUsd', type: 'number', access: 'plain', why: 'Spend below which nothing is ever flagged.' },
  {
    path: 'spendBurn.ceilingUsd',
    type: 'number',
    access: 'plain',
    why: 'Spend above which a run is flagged whatever its comparables say.',
  },
  {
    path: 'spendBurn.floorSteps',
    type: 'number',
    access: 'plain',
    why: 'Tool-using steps below which nothing is ever flagged.',
  },
  {
    path: 'spendBurn.ceilingSteps',
    type: 'number',
    access: 'plain',
    why: 'Steps above which a run is flagged whatever its comparables say.',
  },
  {
    path: 'spendBurn.floorMinutes',
    type: 'number',
    access: 'plain',
    why: 'Minutes below which nothing is ever flagged.',
  },
  {
    path: 'spendBurn.ceilingMinutes',
    type: 'number',
    access: 'plain',
    why: 'Minutes a run may go before it is flagged whatever its comparables say.',
  },
  {
    path: 'runway.enabled',
    type: 'boolean',
    access: 'plain',
    why: 'Say when the queue of work is running out.',
  },
  {
    path: 'runway.warnHours',
    type: 'number',
    access: 'plain',
    why: 'Hours of queued work below which you are told.',
  },
  {
    path: 'runway.clearHours',
    type: 'number',
    access: 'plain',
    why: 'Hours the queue must be back above before the notice clears. Must be above warnHours.',
  },
  {
    path: 'runway.minimumRuns',
    type: 'number',
    access: 'plain',
    why: 'How many finished goals are needed before a typical goal length is known.',
  },
  {
    path: 'pets.enabled',
    type: 'boolean',
    access: 'plain',
    why: 'Creatures that hatch from what you do in the cockpit.',
  },
  {
    path: 'pets.visible',
    type: 'boolean',
    access: 'plain',
    why: 'Show the vivarium and its tab. Off keeps hatching them, out of sight.',
  },
  { path: 'selfUpdate.enabled', type: 'boolean', access: 'plain', why: 'Check this build against its upstream.' },
  { path: 'selfUpdate.remote', type: 'string', access: 'plain', why: 'The remote the build is checked against.' },
  { path: 'selfUpdate.branch', type: 'string', access: 'plain', why: 'The branch the build is checked against.' },
  {
    path: 'selfUpdate.checkIntervalMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How often the upstream tip is read.',
  },
  {
    path: 'selfUpdate.autoUpdate',
    type: 'boolean',
    access: 'plain',
    why: 'Take an update without being asked: drain, then hand off when the fleet is clear.',
  },
  {
    path: 'selfUpdate.drainDeadlineMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How long an automatic drain waits before interrupting what is left. Zero waits forever.',
  },
  {
    path: 'selfUpdate.projectAutoPull',
    type: 'boolean',
    access: 'plain',
    why: 'Fast-forward the worked checkout on its own whenever it cleanly can. Off asks on the rail instead.',
  },
  {
    path: 'selfUpdate.snoozeMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How long Snooze hides an update ask on the rail.',
  },
  {
    path: 'ci.checks',
    type: 'json',
    access: 'plain',
    why: 'What a red check gets, first match wins — so the order is the policy.',
  },
];
