import type { ConfigField } from './configFields.js';

export const TRACKER_FIELDS: readonly ConfigField[] = [
  {
    path: 'integrations.sourceControl',
    type: 'enum',
    options: ['fake', 'github', 'azure'],
    access: 'plain',
    why: 'Which provider fulfils pull requests and branches.',
  },
  {
    path: 'integrations.issues',
    type: 'enum',
    options: ['fake', 'github', 'azure'],
    access: 'plain',
    why: 'Which provider fulfils issues.',
  },
  {
    path: 'integrations.pool',
    type: 'enum',
    options: ['fake', 'git'],
    access: 'plain',
    why: 'Which substrate carries the cross-fleet pool. "fake" publishes nowhere and runs no desk.',
  },
  {
    path: 'userId',
    type: 'string',
    access: 'plain',
    why: 'Who this harness acts as. Tickets it files are assigned to you and its branches are named as yours.',
  },
  {
    path: 'fleetId',
    type: 'string',
    access: 'plain',
    requiredWhen: { path: 'integrations.pool', unless: 'fake' },
    suggest: { join: ['userId', 'pool.project'], with: '@' },
    why: 'Who this fleet is in the pool. Person and target repo, e.g. "alice@acme-api" — never derived.',
  },
  {
    path: 'pool.project',
    type: 'string',
    access: 'plain',
    why: 'What this project is called in the pool. Belongs in the committed lubbdubb.project.json.',
  },
  { path: 'pool.remote', type: 'string', access: 'plain', why: 'The git pool transport’s remote.' },
  { path: 'pool.branch', type: 'string', access: 'plain', why: 'The branch the pool lives on.' },
  {
    path: 'pool.path',
    type: 'string',
    access: 'plain',
    why: 'A prefix inside that repository, so a shared wiki hosts the pool in a folder. Empty is its root.',
  },
  {
    path: 'pool.digestIntervalMs',
    type: 'number',
    ms: true,
    access: 'plain',
    why: 'How often the digest republishes, and how often the backstop re-derives both documents.',
  },
  {
    path: 'ownWorkOnly',
    type: 'boolean',
    access: 'plain',
    why: 'Filter the world to you: pickup needs a watch tag you added, and only pull requests you opened are surfaced.',
  },
  { path: 'github.owner', type: 'string', access: 'plain', why: 'Repository owner (user or org).' },
  { path: 'github.repo', type: 'string', access: 'plain', why: 'Repository name.' },
  {
    path: 'azureDevOps.organization',
    type: 'string',
    access: 'plain',
    why: 'The dev.azure.com/{organization} segment.',
  },
  { path: 'azureDevOps.project', type: 'string', access: 'plain', why: 'Project name — work items are scoped to it.' },
  {
    path: 'azureDevOps.repository',
    type: 'string',
    access: 'plain',
    why: 'Git repository name within the project.',
  },
  {
    path: 'azureDevOps.filters.workItemTag',
    type: 'string',
    access: 'plain',
    why: 'Only surface work items carrying this tag.',
  },
  {
    path: 'azureDevOps.policyChecks',
    type: 'json',
    access: 'plain',
    why: 'Which branch-policy kinds become CI checks, and how.',
  },
  {
    path: 'labelPrefix',
    type: 'string',
    access: 'plain',
    why: 'Derives the ${prefix}-watch tag behind the cockpit’s watch toggle. Empty turns the gate off.',
  },
  {
    path: 'issuePriorityLabels',
    type: 'json',
    access: 'plain',
    why: 'Label → weight, for ordering pickup when headroom is short.',
  },
  {
    path: 'prediction.enabled',
    type: 'boolean',
    access: 'plain',
    why: 'Offer to record a prediction before you first read a plan. A ready plan is drawn obscured with two equal presses; what you write is kept from every agent, and from the tracker above all. Off, nothing is stamped — a goal from before the switch reads as never offered, not as declined.',
  },
  {
    path: 'predictionAggregateMinGoals',
    type: 'number',
    access: 'plain',
    why: 'How many goals a rate needs behind it before the prediction aggregate carries it. Below this the rate is absent from the payload and the count toward it is drawn instead \u2014 the counts themselves are never withheld.',
  },
  {
    path: 'goalCriteria.enabled',
    type: 'boolean',
    access: 'plain',
    why: 'Let you write a goal\u2019s acceptance criteria yourself, versioned and append-only, beside the planner\u2019s own. Criteria written after work started are drift, and drift is surfaced rather than refused.',
  },
  {
    path: 'autoUseAgentDescriptions',
    type: 'boolean',
    access: 'plain',
    why: 'Always use the agent\u2019s description as soon as its pull request opens, as if you had pressed \u201cUse the agent\u2019s\u201d. Your own version still replaces it.',
  },
  {
    path: 'issueSequencing',
    type: 'enum',
    options: ['off', 'links', 'full'],
    access: 'plain',
    why: 'Whether a story waits for the one it depends on. `links` honours the tracker’s own Predecessor links and infers nothing; `off` holds nothing.',
  },
  {
    path: 'issueSequenceMaxChildren',
    type: 'number',
    access: 'plain',
    why: 'Above this many stories a Feature is not sequenced — the prompt would not fit and the order would not be read.',
  },
  {
    path: 'issueStateColours',
    type: 'colourMap',
    access: 'plain',
    why: 'Tracker state → colour for its chip, so a state is one you read rather than one you spell out.',
  },
  {
    path: 'issueBoardStates',
    type: 'stringList',
    access: 'plain',
    why: 'Tracker states as board columns, left to right. Empty = every state the mirror carries.',
  },
  {
    path: 'issueDefaultPriority',
    type: 'number',
    access: 'plain',
    why: 'Weight for an issue carrying no matching priority label.',
  },
  {
    path: 'issuePickupStates',
    type: 'stringList',
    access: 'plain',
    why: 'Only pick up items in these provider-native states. Empty = no state gate.',
  },
  {
    path: 'issueInReviewState',
    type: 'string',
    access: 'plain',
    why: 'State an item moves to once a pull request is open for it.',
  },
  {
    path: 'issueInProgressState',
    type: 'string',
    access: 'plain',
    why: 'State an item moves to once an agent is working it. Do not also list it in the pickup states.',
  },
  {
    path: 'issueCompletedState',
    type: 'string',
    access: 'plain',
    why: 'State a work item moves to when the harness closes it as done. Unset = the harness cannot close items.',
  },
  {
    path: 'issueNotPlannedState',
    type: 'string',
    access: 'plain',
    why: 'State a work item moves to when it is closed as not planned. Unset = a back-out leaves the item open.',
  },
  {
    path: 'issueContainerTypes',
    type: 'stringList',
    access: 'plain',
    why: 'Item types that hold work rather than being work. Their children are the work.',
  },
  {
    path: 'issueParentedTypes',
    type: 'stringList',
    access: 'plain',
    why: 'Item types expected to hang off a container. One of these with no parent is reported as an orphan and you are asked where it belongs; anything else is never asked. List your process template’s names — a type missing here is one no missing-parent question is ever raised for.',
  },
  {
    path: 'issueBugType',
    type: 'string',
    access: 'plain',
    why: 'The work item type a raised bug is filed as. Passed to the provider verbatim.',
  },
  {
    path: 'issueFilingTypes',
    type: 'stringList',
    access: 'plain',
    why: 'The work item types the harness may file. Passed to the provider verbatim.',
  },
];
