import type { ThemeToken } from './tokens.js';

export const DERIVED_TOKENS: readonly ThemeToken[] = [
  {
    name: '--amber-line',
    label: 'Amber border',
    group: 'tints',
    kind: 'colour',
    why: 'The edge of an amber-tinted box',
  },
  {
    name: '--amber-fill',
    label: 'Amber fill',
    group: 'tints',
    kind: 'colour',
    why: 'The ground of an amber-tinted box',
  },
  {
    name: '--withheld-fill',
    label: 'Withheld ground',
    group: 'tints',
    kind: 'colour',
    why: 'The ground of the note that stands where a rate is still below its threshold',
  },
  {
    name: '--withheld-line',
    label: 'Withheld border',
    group: 'tints',
    kind: 'colour',
    why: 'The edge of that note — neutral, because a count toward a threshold is neither a reading nor a warning',
  },
  { name: '--red-line', label: 'Red border', group: 'tints', kind: 'colour', why: 'The edge of a red-tinted box' },
  { name: '--red-fill', label: 'Red fill', group: 'tints', kind: 'colour', why: 'The ground of a red-tinted box' },
  {
    name: '--accent-fill',
    label: 'Accent fill',
    group: 'tints',
    kind: 'colour',
    why: 'The ground of the recovery banner',
  },
  {
    name: '--accent-line',
    label: 'Accent border',
    group: 'tints',
    kind: 'colour',
    why: 'The edge of an accent-tinted box',
  },
  {
    name: '--green-line',
    label: 'Green border',
    group: 'tints',
    kind: 'colour',
    why: 'The edge of a green-tinted box',
  },
  {
    name: '--green-fill',
    label: 'Green fill',
    group: 'tints',
    kind: 'colour',
    why: 'The ground of a green-tinted box',
  },
  { name: '--blue-line', label: 'Blue border', group: 'tints', kind: 'colour', why: 'The edge of a blue-tinted box' },
  {
    name: '--blue-line-2',
    label: 'Blue border, louder',
    group: 'tints',
    kind: 'colour',
    why: 'A blue edge that has to carry on a lit panel',
  },
  { name: '--blue-fill', label: 'Blue fill', group: 'tints', kind: 'colour', why: 'The ground of a blue-tinted box' },
  { name: '--cn-red-bg', label: 'Console red ground', group: 'tints', kind: 'colour', why: 'The body of a red band' },
  {
    name: '--cn-red-fill',
    label: 'Console red fill',
    group: 'tints',
    kind: 'colour',
    why: 'A red chip or a band header',
  },
  { name: '--cn-red-line', label: 'Console red border', group: 'tints', kind: 'colour', why: "A red chip's edge" },
  { name: '--cn-red-ink', label: 'Console red ink', group: 'tints', kind: 'colour', why: 'Words on a red ground' },
  {
    name: '--cn-amber-bg',
    label: 'Console amber ground',
    group: 'tints',
    kind: 'colour',
    why: 'The body of an amber band',
  },
  {
    name: '--cn-amber-fill',
    label: 'Console amber fill',
    group: 'tints',
    kind: 'colour',
    why: 'An amber chip or a band header',
  },
  {
    name: '--cn-amber-line',
    label: 'Console amber border',
    group: 'tints',
    kind: 'colour',
    why: "An amber chip's edge",
  },
  {
    name: '--cn-amber-line-hi',
    label: 'Console amber border, louder',
    group: 'tints',
    kind: 'colour',
    why: 'A pinned or overdue edge',
  },
  {
    name: '--cn-green-bg',
    label: 'Console green ground',
    group: 'tints',
    kind: 'colour',
    why: 'The body of a green band',
  },
  {
    name: '--cn-green-fill',
    label: 'Console green fill',
    group: 'tints',
    kind: 'colour',
    why: 'A green chip or a band header',
  },
  {
    name: '--cn-green-line',
    label: 'Console green border',
    group: 'tints',
    kind: 'colour',
    why: "A green chip's edge",
  },
  {
    name: '--cn-green-ink',
    label: 'Console green ink',
    group: 'tints',
    kind: 'colour',
    why: 'Words on a green ground',
  },
  {
    name: '--cn-blue-bg',
    label: 'Console blue ground',
    group: 'tints',
    kind: 'colour',
    why: 'The body of a blue band',
  },
  {
    name: '--cn-blue-fill',
    label: 'Console blue fill',
    group: 'tints',
    kind: 'colour',
    why: 'A blue chip or a band header',
  },
  { name: '--cn-blue-line', label: 'Console blue border', group: 'tints', kind: 'colour', why: "A blue chip's edge" },
  {
    name: '--cn-blue-line-hi',
    label: 'Console blue border, louder',
    group: 'tints',
    kind: 'colour',
    why: 'A live or watched edge',
  },
  {
    name: '--cn-blue-ink-hi',
    label: 'Console blue ink, louder',
    group: 'tints',
    kind: 'colour',
    why: "The rail's blue lettering",
  },
  {
    name: '--cn-violet-fill',
    label: 'Console violet fill',
    group: 'tints',
    kind: 'colour',
    why: 'A violet chip or a band header',
  },
  {
    name: '--cn-violet-line',
    label: 'Console violet border',
    group: 'tints',
    kind: 'colour',
    why: "A violet chip's edge",
  },
  {
    name: '--cn-captured',
    label: 'Captured, waiting to be looked at',
    group: 'tints',
    kind: 'colour',
    why: 'A validation check whose screen was handed back for somebody to judge — never amber, never green',
  },
  {
    name: '--cn-captured-fill',
    label: 'Captured fill',
    group: 'tints',
    kind: 'colour',
    why: 'The ground behind a captured chip and its row',
  },
  {
    name: '--cn-captured-line',
    label: 'Captured border',
    group: 'tints',
    kind: 'colour',
    why: "A captured chip's edge",
  },
  {
    name: '--cn-readying',
    label: 'Console readying',
    group: 'tints',
    kind: 'colour',
    why: 'Work the harness is readying into an agent',
  },
  {
    name: '--cn-readying-fill',
    label: 'Console readying fill',
    group: 'tints',
    kind: 'colour',
    why: "A readying row's state chip",
  },
  {
    name: '--cn-readying-line',
    label: 'Console readying border',
    group: 'tints',
    kind: 'colour',
    why: "A readying chip's edge",
  },
  {
    name: '--cn-red-ink-hi',
    label: 'Console red ink, louder',
    group: 'tints',
    kind: 'colour',
    why: 'A refusal, and a deleted line in a diff',
  },
  {
    name: '--cn-amber-ink',
    label: 'Console amber ink',
    group: 'tints',
    kind: 'colour',
    why: 'Words on an amber ground',
  },
  {
    name: '--cn-amber-ink-hi',
    label: 'Console amber ink, louder',
    group: 'tints',
    kind: 'colour',
    why: 'The loudest amber lettering',
  },
  {
    name: '--cn-blue-ink',
    label: 'Console blue ink',
    group: 'tints',
    kind: 'colour',
    why: 'Words on a blue ground — leans cyan, not violet',
  },
  { name: '--link-line', label: 'Reference border', group: 'refs', kind: 'colour', why: 'The edge of a reference box' },
  {
    name: '--tier-common-fill',
    label: 'Common tier ground',
    group: 'tints',
    kind: 'colour',
    why: 'The head of a common pet on the Pets page',
  },
  {
    name: '--tier-uncommon-fill',
    label: 'Uncommon tier ground',
    group: 'tints',
    kind: 'colour',
    why: 'The head of an uncommon pet on the Pets page',
  },
  {
    name: '--tier-rare-fill',
    label: 'Rare tier ground',
    group: 'tints',
    kind: 'colour',
    why: 'The head of a rare pet on the Pets page',
  },
  {
    name: '--tier-mythic-fill',
    label: 'Mythic tier ground',
    group: 'tints',
    kind: 'colour',
    why: 'The head of a mythic pet on the Pets page',
  },
  {
    name: '--link-ink',
    label: 'Reference lettering',
    group: 'refs',
    kind: 'colour',
    why: 'The words inside a reference',
  },
  {
    name: '--scrim',
    label: 'Modal scrim',
    group: 'overlays',
    kind: 'colour',
    why: 'What dims the page behind a modal',
  },
  {
    name: '--shadow',
    label: 'Drop shadow',
    group: 'overlays',
    kind: 'colour',
    why: 'The colour under a lifted control',
  },
  {
    name: '--veil',
    label: 'Hover veil',
    group: 'overlays',
    kind: 'colour',
    why: 'The wash over a transcript row under the pointer',
  },
  {
    name: '--scrollbar-track',
    label: 'Scrollbar channel',
    group: 'overlays',
    kind: 'colour',
    why: 'The groove a scrollbar runs in, on every scrolling pane',
  },
  {
    name: '--scrollbar-thumb',
    label: 'Scrollbar thumb',
    group: 'overlays',
    kind: 'colour',
    why: 'The bar you drag',
  },
  {
    name: '--scrollbar-thumb-hover',
    label: 'Scrollbar thumb, hovered',
    group: 'overlays',
    kind: 'colour',
    why: 'The bar you drag, under the pointer',
  },
  {
    name: '--cn-scrim',
    label: 'Console scrim',
    group: 'overlays',
    kind: 'colour',
    why: "The console's own modal dimming",
  },
  {
    name: '--cn-gate-veil',
    label: 'Reveal-gate veil',
    group: 'overlays',
    kind: 'colour',
    why: 'The wash over a plan you have not read yet',
  },
  {
    name: '--cn-unmarked-line',
    label: 'Unmarked edge',
    group: 'tints',
    kind: 'colour',
    why: 'A prediction slot you have not marked yet — an open question, never a miss',
  },
  {
    name: '--cn-hatch-flash',
    label: 'Hatch flash',
    group: 'overlays',
    kind: 'colour',
    why: 'The light a shell comes off in',
  },
];
