/**
 * The cockpit's names for the wire contract.
 *
 * This file used to be a ~840-line hand-maintained mirror of what
 * `buildStateSnapshot` happened to infer, and nothing ever related the two: the
 * producer had no declared return type, this had no producer, and they met at one
 * unchecked `json<AppState>(r)` assertion. It also widened the server's unions
 * three different ways with no rule for which — `Job.status` to `string` (so
 * `j.status === 'queued'` was legal against any string and would silently count
 * zero after a rename), `Proposal.action` to an index-signature bag, and
 * `Finding.status` re-declared member-by-member (so a sixth member server-side
 * left this a silently-narrowing subset).
 *
 * All of it is now one declaration in `src/wire.ts`, which this re-exports. The
 * import is **type-only in both directions**, so nothing about the "web bundle
 * imports no server code" constraint changes: `import type` is erased before the
 * SPA is bundled, and `test/wireContract.test.ts` asserts that structurally.
 *
 * The aliases below are the only translation, and they are aliases rather than
 * copies precisely so they cannot drift: `AppState` is what the cockpit has
 * always called the polled snapshot, and the `*View` names say "this is a payload
 * shape, not the harness's own record" at 40 import sites.
 */
export type {
  Agent,
  AgentAskQuestion,
  AgentFile,
  AgentFlag,
  BugFiling,
  CiHealth,
  CiPolicyDescription,
  CiRuleDescription,
  CiSubject,
  CockpitDecision,
  Decision,
  DispatchRule,
  ErrorLogEntry,
  Escalation,
  FileOverlap,
  FilingTargetProbe,
  Finding,
  EnvironmentGate,
  EnvironmentGateRelease,
  GoalArrival,
  InsightsWindow,
  InsightsWindowView,
  GoalEnvironmentReach,
  GoalReachStatus,
  HumanTask,
  Issue,
  IssueFiled,
  IssueRelative,
  IssueSpend,
  Job,
  JobAttachment,
  JobAttachmentInput,
  JobSchedule,
  Lesson,
  LessonStatus,
  LessonView,
  LocalRunOption,
  LocalRunRefFacts,
  LocalRunTargetView,
  LocalRunView,
  McpChannelPayload,
  OpenPullRequest,
  OrphanedWork,
  AcceptanceCriterion,
  Plan,
  PlanDiff,
  PlanEvidence,
  PlanHistory,
  PlanNarrative,
  PlanPart,
  PlanPartView,
  PlanRevision,
  Pet,
  PetActionKind,
  PetCatalogue,
  PetCatalogueEntry,
  PetCatalogueSource,
  PetRarity,
  PetRules,
  PetSpecies,
  PetStage,
  PetState,
  PetView,
  PlanningPolicy,
  PolicyKindDescription,
  Proposal,
  PullRequest,
  QueueItem,
  RecoveryVerdict,
  BuildReading,
  BuildStanding,
  UpgradeAction,
  ReliabilityInsights,
  RemedyCause,
  RemedyCauseTotal,
  RemedyGuard,
  RemedyInsights,
  RemedyKind,
  RemedyKindHealth,
  RemedyRow,
  RunOutcome,
  RunOutcomeTotal,
  RunPhaseHealth,
  RunRepeat,
  RunTally,
  SupplyState,
  RunningConfigGroup,
  RunningConfigEntry,
  RunningConfigPayload,
  SetupCheck,
  SetupFix,
  SetupPayload,
  SetupResolvePayload,
  SetupVerdict,
  ConfigChange,
  ConfigSavePayload,
  ConfigPreviewPayload,
  SpendGoal,
  SpendInsights,
  SpendPhase,
  SpendPhaseTotal,
  SpendRun,
  SpendTrend,
  SpendTrendComparison,
  SpendTrendPeriod,
  SpendTrendPhaseShift,
  SpendTrendBucket,
  TaskTypeSpend,
  ChecksSpend,
  Stack,
  StackLanding,
  TaskSummary,
  TicketFeatureFacet,
  TicketOrder,
  TicketRow,
  TicketStateFacet,
  TicketStateFilter,
  TicketTrackingFilter,
  TicketWatchFilter,
  TicketsPayload,
  UpcomingPlan,
  ValidationCheck,
  ValidationCheckState,
  ValidationResourceView,
  ValidationVerdict,
  WorldEvent,
  WorldEventKind,
  CockpitState as AppState,
  CockpitWorld as WorldSnapshot,
  PromptTemplateDescription as PromptTemplateView,
  Retrospective as RetrospectiveView,
  ScratchEntry as ScratchEntryView,
  UnrecordedWork as UnrecordedWorkView,
  WorkNode as WorkNodeView,
} from '../../src/wire.js';
