/**
 * The cockpit's names for the wire contract.
 *
 * This file used to be a ~840-line hand-maintained mirror of what
 * `buildStateSnapshot` happened to infer, and nothing ever related the two: the
 * producer had no declared return type, this had no producer, and they met at one
 * unchecked `json<AppState>(r)` assertion. It also widened the server's unions
 * three different ways with no rule for which — `Job.status` to `string` (so
 * `j.status === 'queued'` was legal against any string and would silently count
 * zero after a rename), `Proposal.action` to an index-signature bag, and
 * `Finding.status` re-declared member-by-member (so a sixth member server-side
 * left this a silently-narrowing subset).
 *
 * All of it is now one declaration in `src/wire.ts`, which this re-exports. The
 * import is **type-only in both directions**, so nothing about the "web bundle
 * imports no server code" constraint changes: `import type` is erased before the
 * SPA is bundled, and `test/wireContract.test.ts` asserts that structurally.
 *
 * The aliases below are the only translation, and they are aliases rather than
 * copies precisely so they cannot drift: `AppState` is what the cockpit has
 * always called the polled snapshot, and the `*View` names say "this is a payload
 * shape, not the harness's own record" at 40 import sites.
 */
export type {
  Agent,
  AgentAskQuestion,
  AgentFile,
  AgentFilesPayload,
  AgentFlag,
  AgentTranscript,
  AllowanceApportionment,
  AllowanceGoal,
  AllowanceInsights,
  AllowanceLane,
  AllowancePayload,
  AllowanceProjection,
  AllowanceReading,
  BugFiling,
  CiHealth,
  CiPolicyDescription,
  CiRuleDescription,
  CiSubject,
  CockpitDecision,
  ContradictionRuling,
  Decision,
  DispatchRule,
  ErrorLogEntry,
  Escalation,
  FactLifetime,
  FactReach,
  FactExit,
  FactRuling,
  GraduationOutcome,
  GraduationReading,
  FactScope,
  FileOverlap,
  FilingTargetProbe,
  EnvironmentGate,
  EnvironmentGateRelease,
  EnvironmentHealthReading,
  EnvironmentHealthState,
  EnvironmentHealthTier,
  GoalAgentsPayload,
  GoalArrival,
  InsightsWindow,
  InsightsWindowView,
  GoalEnvironmentReach,
  GoalReachStatus,
  HumanTask,
  Issue,
  IssueFiled,
  IssueRelative,
  IssueSpend,
  Job,
  JobAttachment,
  JobAttachmentInput,
  JobSchedule,
  KnowledgeContradictionView,
  KnowledgeGraduation,
  KnowledgeGraduationView,
  KnowledgeSimilarity,
  KnowledgeCorroboration,
  KnowledgeCost,
  KnowledgeDeliveryView,
  KnowledgeFact,
  KnowledgeFactPayload,
  KnowledgeFactView,
  LocalRunOption,
  LocalRunRefFacts,
  LocalRunTargetView,
  LocalRunView,
  McpChannelPayload,
  McpChannel,
  McpChannelUsage,
  McpInsights,
  McpNaming,
  McpNamingTotal,
  McpPhaseUsage,
  McpQuietTool,
  McpRefusal,
  McpSilentRun,
  McpToolUsage,
  McpUsagePayload,
  PoolInsightsPayload,
  PoolRollup,
  PoolRollupRow,
  PoolStatePayload,
  PoolStatus,
  PoolMirroredClaim,
  PoolFleetReading,
  OpenPullRequest,
  OrphanedWork,
  ViewerAssignment,
  AcceptanceCriterion,
  Plan,
  PlanDiff,
  PlanEvidence,
  PlanHistory,
  PlanNarrative,
  PlanPart,
  PlanPartView,
  PlanRevision,
  Pet,
  PetActionKind,
  PetCatalogue,
  PetCatalogueEntry,
  PetCatalogueSource,
  PetRarity,
  PetRules,
  PetSpecies,
  PetStage,
  PetState,
  PetView,
  PlanningPolicy,
  PolicyKindDescription,
  Proposal,
  PullRequest,
  QueueItem,
  RecoveryVerdict,
  BuildReading,
  BuildStanding,
  UpgradeAction,
  ReliabilityInsights,
  RemedyCause,
  RemedyCauseTotal,
  RemedyGuard,
  RemedyInsights,
  RemedyKind,
  RemedyKindHealth,
  RemedyRow,
  RunClearOut,
  RunOutcome,
  RunOutcomeTotal,
  RunPhaseHealth,
  RunRepeat,
  RunTally,
  SupplyState,
  RunningConfigGroup,
  RunningConfigEntry,
  RunningConfigPayload,
  SetupCheck,
  SetupFix,
  SetupPayload,
  SetupResolvePayload,
  SetupVerdict,
  ConfigChange,
  ConfigSavePayload,
  ConfigPreviewPayload,
  SpendGoal,
  SpendInsights,
  SpendPhase,
  SpendPhaseTotal,
  SpendRun,
  SpendTrend,
  SpendTrendComparison,
  SpendTrendPeriod,
  SpendTrendPhaseShift,
  SpendTrendBucket,
  TaskTypeSpend,
  ChecksSpend,
  Stack,
  StackLanding,
  StateSection,
  TaskSummary,
  FeatureBlockKind,
  FeatureBlockRow,
  FeatureBoardPayload,
  FeatureBriefing,
  FeatureChildRow,
  FeatureChildStanding,
  FeatureCounts,
  FeatureReach,
  FeatureReportRow,
  FeatureRollup,
  FeatureSummary,
  FeatureWorkingRow,
  TicketFeatureFacet,
  TicketOrder,
  TicketRow,
  TicketStateFacet,
  TicketStateFilter,
  TicketTrackingFilter,
  TicketWatchFilter,
  TicketsPayload,
  UpcomingPlan,
  ValidationCheck,
  ValidationCheckState,
  ValidationResourceView,
  ValidationVerdict,
  GoalWatch,
  GoalWatchInput,
  GoalWatchView,
  GoalWatchCheckView,
  WatchCheckVerdict,
  WatchReading,
  WatchReadingVerdict,
  WorldEvent,
  WorldEventKind,
  CockpitState as AppState,
  CockpitWorld as WorldSnapshot,
  PromptTemplateDescription as PromptTemplateView,
  Retrospective as RetrospectiveView,
  ReviewAnchor,
  ReviewAttention,
  ReviewCalibration,
  ReviewCalibrationPayload,
  ReviewOverridePair,
  ReviewOverrideReading,
  ReviewPlumbingPack,
  ReviewPlumbingReading,
  ReviewProminenceReading,
  ReviewClaim,
  ReviewFinding,
  ReviewIdea,
  ReviewMark,
  ReviewMarksPayload,
  ReviewNote,
  ReviewPack,
  ReviewPackAbsence,
  ReviewPackPayload,
  ReviewPackSharing,
  ReviewRange,
  ReviewVerdict,
  ScratchEntry as ScratchEntryView,
  UnrecordedWork as UnrecordedWorkView,
  WorkNode as WorkNodeView,
} from '../../src/wire.js';
